### ISSUE TITLE
Parity 1.4.4 panics with "Tried to insert into filled index" Error

### ISSUE THREAD

**Issue by etherchain-org** [paritytech/parity#3545]
One of my nodes is randomly crashing with the following error message:

```
2016-11-21 10:10:55  Starting Parity/v1.4.4-beta-a68d52c-20161118/x86_64-linux-gnu/rustc1.13.0
2016-11-21 10:10:55  State DB configuation: fast
2016-11-21 10:10:55  Operating mode: active
2016-11-21 10:10:55  Configured for Frontier/Homestead using Ethash engine
2016-11-21 10:11:01  Public node URL: enode://7da7628bbe4c5adf67e95c51d4fdc5cd5177e975f77ac90050206aaccedb857284916440143b40b3d7e6cec462f429cf35e8ce165bdb2a36e2e1be92c0aa5f1f@xxxx:30303
2016-11-21 10:11:02  Imported #2667220 8b45…a4bb (3 txs, 0.19 Mgas, 82.36 ms, 1.32 KiB)
2016-11-21 10:11:11  Imported #2667221 08ed…c288 (0 txs, 0.00 Mgas, 0.69 ms, 0.51 KiB)
2016-11-21 10:11:37      0/24/25 peers     55 MiB db    8 MiB chain  0 bytes queue   20 KiB sync
2016-11-21 10:11:37      0/24/25 peers     55 MiB db    5 MiB chain  0 bytes queue   20 KiB sync
2016-11-21 10:11:51  Imported #2667222 20d2…647d (0 txs, 0.00 Mgas, 0.83 ms, 0.51 KiB)
thread '<unnamed>' panicked at 'Tried to insert into filled index', /home/xxxx/.cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.1.3/src/lib.rs:153
stack backtrace:
   1:      0xb95e0ec2ecf - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:      0xb95e0eca72d - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:      0xb95e0ec908a - std::panicking::default_hook::h0ac3811ec7cee78c
   4:      0xb95e0ec9688 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:      0xb95e08132af - std::panicking::begin_panic::h341b039f84d0b176
   6:      0xb95e08177c6 - <mio::event_loop::EventLoop<H>>::run_once::hd8826d41cd9f3821
   7:      0xb95e081c56f - drop::ha83ce868857a554b
   8:      0xb95e08132d7 - std::panicking::try::do_call::h5376ad9d00b74af5
   9:      0xb95e0ed21f6 - __rust_maybe_catch_panic
  10:      0xb95e081cc44 - <F as alloc::boxed::FnBox<A>>::call_box::ha622049364175089
  11:      0xb95e0ec7e60 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  12:     0x6de2119156f9 - start_thread
  13:     0x6de2123bbb5c - clone
  14:                0x0 - <unknown>
2016-11-21 10:11:53  Imported #2667223 fa80…d224 (0 txs, 0.00 Mgas, 0.74 ms, 0.51 KiB)
2016-11-21 10:12:09  Imported #2667224 ece3…4ff7 (40 txs, 1.08 Mgas, 45.69 ms, 4.97 KiB)

```

**Comment by arkpar** [comment]
What is your `--peers`, `--min-peers`, `--max-peers` settings? Try setting no more than 800 peers for now

**Comment by etherchain-org** [comment]
Sometimes the error message is followed by the following panic

```
2016-11-21 10:29:45  Imported #2667283 b43d…424f (0 txs, 0.00 Mgas, 0.40 ms, 0.51 KiB)
thread '<unnamed>' panicked at 'Tried to insert into filled index', /home/xxx/.cargo/registry/src/github.com-1ecc6299db9ec823/slab-0.1.3/src/lib.rs:153
stack backtrace:
   1:      0x2faea9a7ecf - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:      0x2faea9af72d - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:      0x2faea9ae08a - std::panicking::default_hook::h0ac3811ec7cee78c
   4:      0x2faea9ae688 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:      0x2faea2f82af - std::panicking::begin_panic::h341b039f84d0b176
   6:      0x2faea2fc7c6 - <mio::event_loop::EventLoop<H>>::run_once::hd8826d41cd9f3821
   7:      0x2faea30156f - drop::ha83ce868857a554b
   8:      0x2faea2f82d7 - std::panicking::try::do_call::h5376ad9d00b74af5
   9:      0x2faea9b71f6 - __rust_maybe_catch_panic
  10:      0x2faea301c44 - <F as alloc::boxed::FnBox<A>>::call_box::ha622049364175089
  11:      0x2faea9ace60 - std::sys::thread::Thread::new::thread_start::h759e10bc4abc7e72
  12:     0x716a455656f9 - start_thread
  13:     0x716a4600bb5c - clone
  14:                0x0 - <unknown>
2016-11-21 10:29:52  Finishing work, please wait...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Closed', ../src/libcore/result.rs:799
stack backtrace:
   1:      0x2faea9a7ecf - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:      0x2faea9af72d - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:      0x2faea9ae08a - std::panicking::default_hook::h0ac3811ec7cee78c
   4:      0x2faea9ae688 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:      0x2faea9ae522 - std::panicking::begin_panic::h6ed03353807cf54d
   6:      0x2faea9ae460 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:      0x2faea9ae3e1 - rust_begin_unwind
   8:      0x2faea9eaa0f - core::panicking::panic_fmt::h27224b181f9f037f
   9:      0x2faea934d35 - core::result::unwrap_failed::h285159861d436a06
  10:      0x2faea948879 - hyper::server::Listening::close::had01cb0d9bb5c8cc
  11:      0x2faea317239 - <jsonrpc_http_server::Server as core::ops::Drop>::drop::h08ef222042fc5e94
  12:      0x2faea0bfd1f - drop::h00e9298469b9f544
  13:      0x2faea1ad59c - parity::run::execute::hf02bc239ef95fc94
  14:      0x2faea1b6163 - parity::execute::h6ed3493befe74622
  15:      0x2faea1c2c8d - parity::main::h9e2dd1baf3efb2c6
  16:      0x2faea9b71f6 - __rust_maybe_catch_panic
  17:      0x2faea9ad901 - std::rt::lang_start::h538f8960e7644c80
  18:     0x716a45f2582f - __libc_start_main
  19:      0x2faea00b56d - <unknown>
  20:                0x0 - <unknown>
```

I am using the following command line to start parity:
`parity --relay-set strict --force-sealing --cache-size-db 1024 --gas-floor-target 2000000 --gasprice 20000000000 --gas-cap 2000000 --jsonrpc-hosts all --extra-data "xxxx" --reseal-on-txs "none" --author 0xxxxx --port 30303 --rpcport 8546 --pruning-history 1200`

**Comment by arkpar** [comment]
@tomusdrw Could be it can't handle too many RPC connections?

**Comment by etherchain-org** [comment]
I have now downgraded the node to v1.3.13 and so far did not experience the issue.

**Comment by tomusdrw** [comment]
RPC connections issue seems likely, @etherchain-org  are you using `:8485` or `:8080` for RPC?

**Comment by etherchain-org** [comment]
I am using `--rpcport 8546`

**Comment by tomusdrw** [comment]
Is 10 req/sec number of requests that you are making or that the node is handling?
(The question is: is it possible that there is a lot of pending requests and Parity is not able to process them fast enough?)

**Comment by etherchain-org** [comment]
I am making around 10 req/sec. After evaluating the errors in my system I think the node is unable to handle them properly, hence the L4 timeout errors. I have a similar setup on two other servers (both on SSD drives) that works without issues.

**Comment by tomusdrw** [comment]
I think the difference is that in `1.3.x` we were accepting request, processing it and returning a response in the same thread, so the server was not accepting more connections than it could handle.
In `1.4.x` we accept connection and process request asynchronously, so in the meantime we can accept more connections.

**Comment by etherchain-org** [comment]
I have just experienced the same issue on a node with close to 0 RPC load (~1 req / second).

Do you already have a fix available to test for this problem?

**Comment by tomusdrw** [comment]
I was unable to reproduce the problem, could you try this test on your machine to confirmt that it's the number of requests causing ?

```bash
# Setup a new filter
$ curl -X POST -HContent-type:application/json --data '{
	"jsonrpc": "2.0",
	"id": "1",
	"method": "eth_newFilter",
	"params": [{
		"fromBlock": "earliest",
		"toBlock": "latest",
		"limit": 1024
	}]
}' localhost:8545

# Create data.json
$ echo '{
 "jsonrpc": "2.0",
 "id": "1",
 "method": "eth_getFilterLogs",
 "params": ["0x0"]
 }' > data.json

# Run ab testing tool (would be best to run it on a separate machine)
$ ab \
	-c 100 \
	-n 10000 \
	-p ./data.json \
	-T "application/json" \
	http://localhost:8545/

``

**Comment by tomusdrw** [comment]
Is it possible that you have some `eth_sendTransaction` requests run against this node that never get's confirmed via Signer?

**Comment by ppratscher** [comment]
@tomusdrw The node is just used for mining and has no accounts loaded. The only RPC calls used are getWork, eth_syncing and getBlock.

**Comment by etherchain-org** [comment]
@tomusdrw 

I have executed your test case but using only eth_getWork calls, as this is what most of my RPC calls consist of. The test did not trigger the panic. You can find the full logs below:

```
This is ApacheBench, Version 2.3 <$Revision: 1706008 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 1000 requests
Completed 2000 requests
Completed 3000 requests
Completed 4000 requests
Completed 5000 requests
Completed 6000 requests
Completed 7000 requests
Completed 8000 requests
Completed 9000 requests
Completed 10000 requests
Finished 10000 requests


Server Software:
Server Hostname:        localhost
Server Port:            8546

Document Path:          /
Document Length:        265 bytes

Concurrency Level:      100
Time taken for tests:   0.660 seconds
Complete requests:      10000
Failed requests:        0
Total transferred:      4630000 bytes
Total body sent:        2110000
HTML transferred:       2650000 bytes
Requests per second:    15154.59 [#/sec] (mean)
Time per request:       6.599 [ms] (mean)
Time per request:       0.066 [ms] (mean, across all concurrent requests)
Transfer rate:          6852.13 [Kbytes/sec] received
                        3122.67 kb/s sent
                        9974.80 kb/s total

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.4      0       5
Processing:     1    6   1.1      6      12
Waiting:        1    4   0.9      4       9
Total:          3    7   1.1      6      12

Percentage of the requests served within a certain time (ms)
  50%      6
  66%      6
  75%      7
  80%      7
  90%      8
  95%      9
  98%     10
  99%     11
 100%     12 (longest request)
```

The test was executed against the latest Parity beta version.

**Comment by tomusdrw** [comment]
Thanks for tests results, looks like everything is fine and the node is responding fast.

There is a PR (#3627) pending updating `hyper`, `mio` and `slab` packages (basically the core HTTP server stack) to latest versions, hopefuly (I still wasn't able to reproduce) fixing the problem.

**Comment by 5chdn** [comment]
@etherchain-org does this still happen?
