### ISSUE TITLE
Can I use web3.shh with Parity client?

### ISSUE THREAD

**Issue by ruchevits** [paritytech/parity#5515]
I'm trying to whisper a message using web3.shh following the example here: https://github.com/paritytech/parity/wiki/Whisper-Overview

```js
web3.shh.post({ "topic": 't', "payload": 'p'});
```

And it throws an error:

```
Error: Method not found
      at Object.InvalidResponse (/node_modules/web3/lib/web3/errors.js:35:16)
      at RequestManager.send (/node_modules/web3/lib/web3/requestmanager.js:61:22)
      at Shh.send [as post] (/node_modules/web3/lib/web3/method.js:145:58)
      at Context.done (test/index.js:33:23)
```
My Parity client is running with the following arguments:

```bash
parity -l all \
       --mode "active" \
       --unlock $ALICE,$BOB \
       --password $CONFIG_DIR/password \
       --chain $CHAINS_DIR/$CHAIN \
       --db-path $DB_PATH \
       --keys-path $DB_PATH/keys \
       --identity $IDENTITY \
       --no-discovery \
       --reserved-peers $CONFIG_DIR/peers.enodes \
       --jsonrpc-port "8545" \
       --jsonrpc-interface "0.0.0.0" \
       --jsonrpc-apis "web3,eth,net,parity,parity_accounts,parity_set,traces,rpc,personal,signer" \
       --jsonrpc-hosts "all" \
       --author $COINBASE \
       --reseal-min-period "10" \
       --ui-interface "0.0.0.0" \
       --ui-port "8180" \
       --ui-no-validation \
       $*
```

Parity version: `x86_64-unknown-debian-gnu/parity_1.7.0_amd64.deb`
Web3 version: `0.18.4`

Also asked on Ethereum SE: https://ethereum.stackexchange.com/questions/15527/can-i-use-web3-shh-with-parity-client

**Comment by rphmeier** [comment]
Hi @ruchevits, 

Whisper support hasn't landed yet, but we are targeting it for the 1.8 release. The wiki pages are up as design documents and references as opposed to tutorials, but I understand the confusion!
