### ISSUE TITLE
Cann't sync blocks

### ISSUE THREAD

**Issue by u2** [paritytech/parity#5772]
I started sync blocks from genesis yesterday, now it stuck at #1903086

I try to restart it, but it does not work.

```
2017-06-06 12:03:46  Syncing #1898165 4db4…6de2   193 blk/s 1003 tx/s  28 Mgas/s      0+ 1471 Qed  #1899637    2/ 7/25 peers   106 MiB db   10 MiB chain   10 MiB queue    7 MiB sync  RPC:  0 conn, 151 req/s, 165 µs
2017-06-06 12:03:56  Syncing #1899531 338d…c5a5   136 blk/s  895 tx/s  23 Mgas/s      0+ 1246 Qed  #1900780    2/ 7/25 peers   107 MiB db   10 MiB chain    7 MiB queue    7 MiB sync  RPC:  0 conn, 212 req/s, 165 µs
2017-06-06 12:04:02  Syncing #1900326 2b6a…b3ad   162 blk/s  686 tx/s  16 Mgas/s      0+ 1085 Qed  #1901495    3/ 7/25 peers   107 MiB db    7 MiB chain    6 MiB queue    7 MiB sync  RPC:  0 conn, 166 req/s, 165 µs
2017-06-06 12:04:11  Syncing #1901647 3196…d5fb   135 blk/s  567 tx/s  15 Mgas/s      0+ 1162 Qed  #1902812    3/ 6/25 peers   107 MiB db    6 MiB chain    7 MiB queue    7 MiB sync  RPC:  0 conn, 133 req/s, 165 µs
2017-06-06 12:04:17  Syncing #1902014 4eec…6389    74 blk/s  257 tx/s   8 Mgas/s      0+ 1175 Qed  #1903193    3/ 6/25 peers   107 MiB db    7 MiB chain    8 MiB queue    7 MiB sync  RPC:  0 conn,  1 req/s, 169 µs
2017-06-06 12:04:26  Syncing #1903034 4f68…1b43   102 blk/s  630 tx/s  16 Mgas/s      0+ 1262 Qed  #1904300    3/ 6/25 peers   107 MiB db    6 MiB chain    8 MiB queue    7 MiB sync  RPC:  0 conn, 167 req/s, 169 µs
thread 'IO Worker #0' panicked at 'index 4525080863194260229 out of range for slice of length 0', src/libcore/slice/mod.rs:721
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::slice::slice_index_len_fail
   9: <ethcore::evm::interpreter::Interpreter<Cost>>::copy_data_to_memory
  10: <ethcore::evm::interpreter::Interpreter<Cost>>::exec_instruction
  11: <ethcore::evm::interpreter::Interpreter<Cost> as ethcore::evm::evm::Evm>::exec
  12: <ethcore::executive::Executive<'a, B>>::exec_vm
  13: <ethcore::executive::Executive<'a, B>>::create
  14: <ethcore::executive::Executive<'a, B>>::transact
  15: ethcore::block::OpenBlock::push_transaction
  16: ethcore::block::enact
  17: ethcore::block::enact_verified
  18: ethcore::client::client::Client::import_verified_blocks
[1]    6631 abort      ./target/release/parity

# u2 at localhost in ~/soft/parity on git:e12841814 x [12:04:27]
$ ./target/release/parity
2017-06-06 15:39:52  Starting Parity/v1.7.0-unstable-de4c9507e-20170529/x86_64-macos/rustc1.19.0-nightly
2017-06-06 15:39:52  State DB configuration: fast
2017-06-06 15:39:52  Operating mode: active
2017-06-06 15:39:52  Configured for Foundation using Ethash engine
2017-06-06 15:39:55  Updated conversion rate to Ξ1 = US$256.43 (464250000 wei/gas)
2017-06-06 15:39:55  Removed existing file '/Users/u2/Library/Application Support/io.parity.ethereum/jsonrpc.ipc'.
2017-06-06 15:40:00  Public node URL: enode://694e0f78411bcd899baf09a4f4958017fefd821acb20942031057ab143028e517979722dc2dd43c6c2dc2ff094db661a596dbba0d0d9b2bcba837d9a1711761f@192.168.199.4:30303
2017-06-06 15:40:00  Syncing #1903086 0486…3c74     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #1903086    0/ 1/25 peers    66 MiB db  217 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:40:30     0/ 2/25 peers    66 MiB db  698 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:41:00     0/ 3/25 peers    66 MiB db    1 MiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:41:30     0/ 3/25 peers    66 MiB db    1 MiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:42:00     0/ 5/25 peers    66 MiB db    3 MiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:42:25  Syncing #1903086 0486…3c74     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #1903086    2/ 8/25 peers    66 MiB db    3 MiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
thread 'Verifier #2' panicked at 'index 4525080863194260229 out of range for slice of length 0', src/libcore/slice/mod.rs:721
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::slice::slice_index_len_fail
   9: <ethcore::evm::interpreter::Interpreter<Cost>>::copy_data_to_memory
  10: <ethcore::evm::interpreter::Interpreter<Cost>>::exec_instruction
  11: <ethcore::evm::interpreter::Interpreter<Cost> as ethcore::evm::evm::Evm>::exec
  12: <ethcore::executive::Executive<'a, B>>::exec_vm
  13: <ethcore::executive::Executive<'a, B>>::create
  14: <ethcore::executive::Executive<'a, B>>::transact
  15: ethcore::block::OpenBlock::push_transaction
  16: ethcore::block::enact
  17: ethcore::block::enact_verified
  18: ethcore::client::client::Client::import_verified_blocks
  19: <ethcore_io::service::IoChannel<Message>>::send_sync
  20: ethcore::verification::queue::QueueSignal::set_sync
[1]    17890 abort      ./target/release/parity

# u2 at localhost in ~/soft/parity on git:e12841814 x [15:42:29]
$ ./target/release/parity
2017-06-06 15:42:37  Starting Parity/v1.7.0-unstable-de4c9507e-20170529/x86_64-macos/rustc1.19.0-nightly
2017-06-06 15:42:37  State DB configuration: fast
2017-06-06 15:42:37  Operating mode: active
2017-06-06 15:42:37  Configured for Foundation using Ethash engine
2017-06-06 15:42:38  Updated conversion rate to Ξ1 = US$256.58 (463978560 wei/gas)
2017-06-06 15:42:39  Removed existing file '/Users/u2/Library/Application Support/io.parity.ethereum/jsonrpc.ipc'.
2017-06-06 15:42:44  Public node URL: enode://694e0f78411bcd899baf09a4f4958017fefd821acb20942031057ab143028e517979722dc2dd43c6c2dc2ff094db661a596dbba0d0d9b2bcba837d9a1711761f@192.168.199.4:30303
2017-06-06 15:43:14     0/ 0/25 peers    66 MiB db  434 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:43:44     0/ 1/25 peers    66 MiB db  998 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:44:19     0/ 1/25 peers    66 MiB db    1 MiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-06 15:44:29  Syncing #1903088 2f69…83f1     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #1903088    2/ 3/25 peers    66 MiB db    2 MiB chain  0 bytes queue   19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
thread 'Verifier #0' panicked at 'index 4525080863194260229 out of range for slice of length 0', src/libcore/slice/mod.rs:721
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::slice::slice_index_len_fail
   9: <ethcore::evm::interpreter::Interpreter<Cost>>::copy_data_to_memory
  10: <ethcore::evm::interpreter::Interpreter<Cost>>::exec_instruction
  11: <ethcore::evm::interpreter::Interpreter<Cost> as ethcore::evm::evm::Evm>::exec
  12: <ethcore::executive::Executive<'a, B>>::exec_vm
  13: <ethcore::executive::Executive<'a, B>>::create
  14: <ethcore::executive::Executive<'a, B>>::transact
  15: ethcore::block::OpenBlock::push_transaction
  16: ethcore::block::enact
  17: ethcore::block::enact_verified
  18: ethcore::client::client::Client::import_verified_blocks
  19: <ethcore_io::service::IoChannel<Message>>::send_sync
  20: ethcore::verification::queue::QueueSignal::set_sync
[1]    17932 abort      ./target/release/parity
```

**Comment by MeD1aToR** [comment]
**Parity/v1.7.0-unstable-0e36dee-20170608/x86_64-linux-gnu/rustc1.17.0**
Aborted on restart
```
thread 'Verifier #0' panicked at 'index 4525080863194260229 out of range for slice of length 0', /checkout/src/libcore/slice.rs:578
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::slice::slice_index_len_fail
             at /checkout/src/libcore/slice.rs:578
  10: <ethcore::evm::interpreter::Interpreter<Cost>>::copy_data_to_memory
  11: <ethcore::evm::interpreter::Interpreter<Cost>>::exec_instruction
  12: <ethcore::evm::interpreter::Interpreter<Cost> as ethcore::evm::evm::Evm>::exec
  13: <ethcore::executive::Executive<'a, B, E>>::exec_vm
  14: <ethcore::executive::Executive<'a, B, E>>::create
  15: <ethcore::executive::Executive<'a, B, E>>::transact
  16: ethcore::block::OpenBlock::push_transaction
  17: ethcore::block::enact
  18: ethcore::client::client::Client::import_verified_blocks
  19: <ethcore_io::service::IoChannel<Message>>::send_sync
  20: ethcore::verification::queue::QueueSignal::set_sync
  21: std::panicking::try::do_call
  22: <unknown>
             at /checkout/src/libpanic_abort/lib.rs:40
```
