### ISSUE TITLE
Verifier panicked, ethabi is correct, qed invalid data

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity#5792]
Hi everyone,
I'm trying to set up a test private PoA network where signers are added via a contract
```
...
  "engine": {
    "authorityRound": {
      "params": {
        "gasLimitBoundDivisor": "0x400",
        "stepDuration": "5",
        "validators": {
          "contract": "0xabcdef...."
        }
      }
    }
  },
...
```
Initially there was a single node, then I created a new signer account, and tried to setup a separate miner node for it. But it fails trying to sync 0th block:
```
Loading config file from node.toml
2017-06-07 17:04:19 UTC Starting Parity/v1.7.0-nightly-badb372-20170320/x86_64-linux-gnu/rustc1.16.0
2017-06-07 17:04:19 UTC State DB configuration: fast
2017-06-07 17:04:19 UTC Operating mode: active
2017-06-07 17:04:19 UTC Updated conversion rate to Ξ1 = US$262.05 (454293570 wei/gas)
2017-06-07 17:04:20 UTC Configured for OraclesPoA using AuthorityRound engine
2017-06-07 17:04:20 UTC *** INSECURE *** Running Trusted Signer with no origin validation.
2017-06-07 17:04:20 UTC If you do not intend this, exit now.
2017-06-07 17:04:26 UTC Syncing       #0 d982…89cf     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    0/ 1/25 peers     8 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-07 17:04:26 UTC Public node URL: enode://abcdef...@172.17.0.2:30300
thread 'Verifier #0' panicked at 'ethabi is correct; qed: InvalidData', /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:868
stack backtrace:
   1:     0x5615cce4cb4c - <unknown>
   2:     0x5615cce5403e - <unknown>
   3:     0x5615cce53c44 - <unknown>
   4:     0x5615cce544db - <unknown>
   5:     0x5615cce54374 - <unknown>
   6:     0x5615cce54299 - <unknown>
   7:     0x5615cce54227 - <unknown>
   8:     0x5615cce80f1d - <unknown>
   9:     0x5615cc889097 - <unknown>
  10:     0x5615cc977a42 - <unknown>
  11:     0x5615cc9763d4 - <unknown>
  12:     0x5615cc9771e4 - <unknown>
  13:     0x5615cc977a68 - <unknown>
  14:     0x5615cc966979 - <unknown>
  15:     0x5615cca2a27b - <unknown>
  16:     0x5615cca2de84 - <unknown>
  17:     0x5615cc98b162 - <unknown>
  18:     0x5615cc8b0932 - <unknown>
  19:     0x5615cca2cc41 - <unknown>
  20:     0x5615cc836b12 - <unknown>
  21:     0x5615cce5b0fb - <unknown>
```
Probably there is a misconfiguration on my part, but it'd be nice to get a correct error message.
If I copy `chain` folder from the initial node to the second one, it starts OK and syncs.
Also note that I'm running parity via docker image ethcore/parity.

**Comment by keorn** [comment]
I notice you run an old nightly. First I would advise running the latest `beta`, then making sure that your validator contract conforms to [the ABI](https://github.com/paritytech/parity/wiki/Validator-Set#contracts)

**Comment by 5chdn** [comment]
Please report back if this issue persists with latest nightly or beta.

**Comment by rphmeier** [comment]
The state of validator contracts on nightly is still in flux. For now it's better just to have `getValidators` function and use beta.

**Comment by phahulin** [comment]
@keorn @rphmeier Which version exactly do you mean by beta https://github.com/paritytech/parity/releases/tag/v1.6.8 this one?

**Comment by rphmeier** [comment]
yep, the 1.6.x channel is our current beta release

**Comment by phahulin** [comment]
I'm compiling 1.6.8 now, meanwhile, I've tested on 1.6.6 from docker image ethcore/parity:beta-release and on 1.6.7-beta outside docker (directly on host) with sync trace, here's the log:
```
Loading config file from node.toml
2017-06-08 14:18:54 UTC main INFO parity::run  Starting Parity/v1.6.7-beta-e128418-20170518/x86_64-linux-gnu/rustc1.17.0
2017-06-08 14:18:54 UTC main INFO parity::run  State DB configuration: fast
2017-06-08 14:18:54 UTC main INFO parity::run  Operating mode: active
2017-06-08 14:18:54 UTC hyper-client INFO miner  Updated conversion rate to Ξ1 = US$256.83 (463526900 wei/gas)
2017-06-08 14:18:54 UTC main INFO ethcore::service  Configured for OraclesPoA using AuthorityRound engine
2017-06-08 14:18:55 UTC main WARN parity::signer  *** INSECURE *** Running Trusted Signer with no origin validation.
2017-06-08 14:18:55 UTC main INFO parity::signer  If you do not intend this, exit now.
2017-06-08 14:18:56 UTC IO Worker #2 TRACE sync  == Connected 0: Parity/v1.6.7-beta-e128418-20170518/x86_64-linux-gnu/rustc1.17.0
2017-06-08 14:18:56 UTC IO Worker #2 TRACE sync  Sending status to 0, protocol version 2
2017-06-08 14:18:56 UTC IO Worker #3 TRACE sync  New peer 0 (protocol: 2, network: 8995, difficulty: Some(1441792), latest:2069…5950, genesis:d982…89cf, snapshot:Some(0))
2017-06-08 14:18:56 UTC IO Worker #3 DEBUG sync  Connected 0:Parity/v1.6.7-beta-e128418-20170518/x86_64-linux-gnu/rustc1.17.0
2017-06-08 14:18:56 UTC IO Worker #3 TRACE sync  Checking snapshot sync: 0 vs 0
2017-06-08 14:19:00 UTC IO Worker #3 INFO import  Syncing       #0 d982…89cf     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    0/ 1/25 peers     8 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-06-08 14:19:01 UTC IO Worker #3 INFO network  Public node URL: enode://abcdef...@10.0.0.4:30300
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  No snapshots found, starting full sync
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  Syncing with peers: 1 active, 1 confirmed, 1 total
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  Considering peer 0, force=false, td=Some(1441792), our td=131072, latest=2069…5950, have_latest=false, state=Idle
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  Syncing with peer 0, force=false, td=Some(1441792), our td=131072, state=Idle
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  Starting round (last imported count = None, last started = 0, block = 0
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  Starting sync with better chain
2017-06-08 14:19:03 UTC IO Worker #0 TRACE sync  0 <- GetBlockHeaders: 256 entries starting from d982…89cf, set = NewBlocks
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  0 -> BlockHeaders (1 entries), state = Blocks, set = NewBlocks
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Header already in chain 0 (d982…89cf), state = ChainHead
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Received 1 subchain heads, proceeding to download
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Imported 0 of 0
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Considering peer 0, force=false, td=Some(1441792), our td=131072, latest=2069…5950, have_latest=false, state=Blocks
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Syncing with peer 0, force=false, td=Some(1441792), our td=131072, state=Blocks
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  0 <- GetBlockHeaders: 128 entries starting from d982…89cf, set = NewBlocks
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Syncing with peers: 1 active, 1 confirmed, 1 total
2017-06-08 14:19:03 UTC IO Worker #3 TRACE sync  Skipping busy peer 0
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  0 -> BlockHeaders (11 entries), state = Blocks, set = NewBlocks
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Header already in chain 0 (d982…89cf)
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New head d982…89cf
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: d98294d99f3c03e14450107ab49c7e8dfc39a8dd42a4c4081c62c721828989cf
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: e719f13cc96144238fb3fdc9abdcf72306d2defe743a4f204ac7bf7f09fc9b3c
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: e70b065eff6b7dd45f1cf81f2c9f3ea112c3fbd6325fb91c2aee8dfc01419970
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 05f893f0490861c8f80b3dc8a959de0deae7bb9a1e2f46b2e70bf36fccc5d3b1
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 81d4b06f499a4751daf9c2b5ceecdc6b74cfccd82a894287ea7203c46f0ac8ca
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 9ec5115db512771a7c665fdce7f0dcced0a8a18fc11b862af99bd7896583a342
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: aa4d13a1dbfc4b6c35d53183a23570780d0c4631d94ba24a319a76cb1d0b600b
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 7a674d11451b758efcb7580950a89783fc41dd8a1b75138da214138d6e88a61d
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 937ac3d76fa94624256971d1479414d57830c299878c2191ad1361f804c795d1
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 10594f36577dfcd53e2e63106de031632d996550fd9b53e324620841cdfc918f
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  New header: 20695587aa2ca3c1fbdbd54fef4f31b54a25eaf80dae1654bba70a2f78f95950
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Inserted 11 headers
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Drained 1 blocks, new head :Some(d98294d99f3c03e14450107ab49c7e8dfc39a8dd42a4c4081c62c721828989cf)
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Block already in chain d98294d99f3c03e14450107ab49c7e8dfc39a8dd42a4c4081c62c721828989cf
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Imported 0 of 1
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Considering peer 0, force=false, td=Some(1441792), our td=131072, latest=2069…5950, have_latest=false, state=Blocks
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Syncing with peer 0, force=false, td=Some(1441792), our td=131072, state=Blocks
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  0 <- GetBlockBodies: 10 entries starting from Some(e719f13cc96144238fb3fdc9abdcf72306d2defe743a4f204ac7bf7f09fc9b3c), set = NewBlocks
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Syncing with peers: 1 active, 1 confirmed, 1 total
2017-06-08 14:19:03 UTC IO Worker #2 TRACE sync  Skipping busy peer 0
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  0 -> BlockBodies (10 entries), set = NewBlocks
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body e719…9b3c
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body e70b…9970
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 05f8…d3b1
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 81d4…c8ca
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 9ec5…a342
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body aa4d…600b
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 7a67…a61d
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 937a…95d1
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 1059…918f
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Got body 2069…5950
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Drained 10 blocks, new head :Some(20695587aa2ca3c1fbdbd54fef4f31b54a25eaf80dae1654bba70a2f78f95950)
thread 'Verifier #0' panicked at 'ethabi is correct; qed: InvalidData', /checkout/src/libcore/result.rs:859
stack backtrace:
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued e719f13cc96144238fb3fdc9abdcf72306d2defe743a4f204ac7bf7f09fc9b3c
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued e70b065eff6b7dd45f1cf81f2c9f3ea112c3fbd6325fb91c2aee8dfc01419970
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 05f893f0490861c8f80b3dc8a959de0deae7bb9a1e2f46b2e70bf36fccc5d3b1
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 81d4b06f499a4751daf9c2b5ceecdc6b74cfccd82a894287ea7203c46f0ac8ca
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 9ec5115db512771a7c665fdce7f0dcced0a8a18fc11b862af99bd7896583a342
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued aa4d13a1dbfc4b6c35d53183a23570780d0c4631d94ba24a319a76cb1d0b600b
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 7a674d11451b758efcb7580950a89783fc41dd8a1b75138da214138d6e88a61d
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 937ac3d76fa94624256971d1479414d57830c299878c2191ad1361f804c795d1
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 10594f36577dfcd53e2e63106de031632d996550fd9b53e324620841cdfc918f
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Block queued 20695587aa2ca3c1fbdbd54fef4f31b54a25eaf80dae1654bba70a2f78f95950
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Imported 10 of 10
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Sync round complete
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Skipping peer 0, force=false, td=Some(1441792), our td=1441792, state=Blocks
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Syncing with peers: 1 active, 1 confirmed, 1 total
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Skipping peer 0, force=false, td=Some(1441792), our td=1441792, state=Blocks
2017-06-08 14:19:03 UTC IO Worker #1 TRACE sync  Sync complete
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
```
Maybe this will help. As soon as I get test result from 1.6.8 I'll post it here

**Comment by phahulin** [comment]
I've also tested on a newly release 1.6.8. Same error repeats. Here is the [err.txt](https://github.com/paritytech/parity/files/1063574/err.txt).
@keorn please reopen this issue.

**Comment by phahulin** [comment]
Here are some additional logs obtained with `parity -l trace` [verifier_0.txt](https://github.com/paritytech/parity/files/1064520/verifier_0.txt)

**Comment by rphmeier** [comment]
@phahulin could you post contract source?

**Comment by phahulin** [comment]
[Here](https://github.com/oraclesorg/oracles-contract)'s the link to the contract's repo.

Specifically, only methods `addInitialKey` and then `createKeys` from [this file](https://github.com/oraclesorg/oracles-contract/blob/master/src/KeysManager.sol) had been called before we tried to start the sync on the second signer's node.

**Comment by rstormsf** [comment]
+1. Can someone plz let me know if it's being confirmed and someone is working on it

**Comment by keorn** [comment]
If [this](https://github.com/oraclesorg/oracles-contract/blob/master/src/ValidatorsManager.sol) is the contract, then it does not conform to the required ABI as the error indicates.
Have a look at the [documentation](https://github.com/paritytech/parity/wiki/Validator-Set#reporting-contract).

@rphmeier should it work with just `getValidators`? [Source for 1.6.8](https://github.com/paritytech/parity/tree/08436a7124b454165d8fb27bda4038bb646c37fe/ethcore/native_contracts/res)

**Comment by rphmeier** [comment]
Under 1.6.8 all that's required is a `getValidators` function. On nightly the ABI is different and undergoing changes.

**Comment by keorn** [comment]
Can you confirm the contract and spec that you are using?

**Comment by phahulin** [comment]
@keorn Probably there is a misconfiguration, could you please verify the steps we take (we try to follow [this guide](https://github.com/paritytech/parity/wiki/Validator-Set#contracts))
1. compile the contract, use its binary code to get hex-representation of the code (e.g. "0xc0de...")
2. open genesis.json and add 
```
"validators": {
      "contract": "0xc0412ac1..."
}
```
Can we use any (valid) address here?
3. add the corresponding entry to "accounts":
```
"0xc0412ac1...": {
    "balance": 1,
    "constructor": "0xc0de..."
}
```
4. this is it, start parity? Should we additionally deploy the contract somehow?

**Comment by keorn** [comment]
There is no need to deploy the contract, `"constructor"` already takes care of that. Otherwise these steps look good. I need to replicate the issue to figure out where is the issue. Can you provide the contract I should compile?
It might be due to the lack of misbehaviour reporting functions. You can try `safeContract` instead of `contract` in the spec.

**Comment by phahulin** [comment]
@keorn thanks, we've double checked our configuration from scratch and found a mistake in "constructor" field - it was filled with hex representation of the contract's binary file, while it must have been filled with its actual context (which is already in hex).
We've also switched to "safeContract".
This issue may be closed now.

**Comment by keorn** [comment]
Cool
