### ISSUE TITLE
Build failed. Debian/Armhf, panicked at 'explicit panic'

### ISSUE THREAD

**Issue by julian1** [paritytech/parity#5841]
```
$ uname -a
Linux pi-1 4.9.0-3-armmp-lpae #1 SMP Debian 4.9.30-1 (2017-06-04) armv7l GNU/Linux

$ git status
HEAD detached at v1.6.8

$ cargo version
cargo 0.19.0 (28d1d60d4 2017-05-16)

$ time cargo build --release -vv 2>&1 | tee log 

HOST = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("armv7-unknown-linux-gnueabihf")
CXXFLAGS_armv7-unknown-linux-gnueabihf = None
CXXFLAGS_armv7_unknown_linux_gnueabihf = None
HOST_CXXFLAGS = None
CXXFLAGS = None
running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-march=armv7-a" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "snappy/" "-I" "." "-std=c++11" "-DNDEBUG=1" "-DSNAPPY=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/home/parity/parity/target/release/build/rocksdb-sys-73ff07967ffa277b/out/rocksdb/table/plain_table_key_coding.o" "-c" "rocksdb/table/plain_table_key_coding.cc"
ExitStatus(ExitStatus(0))
ExitStatus(ExitStatus(0))

--- stderr
thread '<unnamed>' panicked at 'explicit panic', /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/gcc-0.3.35/src/lib.rs:897
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread '<unnamed>' panicked at 'job function panicked', /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-0.4.2/src/job.rs:60
thread 'main' panicked at 'job function panicked', /home/parity/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-0.4.2/src/job.rs:60

Build failed, waiting for other jobs to finish...
^C

real    33m56.600s
user    0m0.045s
sys     0m0.695s
```

explicit panic error looks similar to https://github.com/paritytech/parity/issues/5794

**Comment by julian1** [comment]
It builds successfully when using a single thread, ie using the -j 1 flag

```
$ time cargo build -j 1 --release -vv 2>&1 | tee log 
/ring-75f3a2d109f1fb35/out`
    Finished release [optimized] target(s) in 17650.87 secs

real    294m24.806s
user    290m19.845s
sys     3m48.645s
```

I am going to close this issue, because I can't rule out that it's not hardware related, and it looks like the problem arises very deep in the cargo/rust build system, rather than parity code.
