### ISSUE TITLE
Parity RlpExpectedToBeData

### ISSUE THREAD

**Issue by mantoshelis** [paritytech/parity#6090]
Can't make Parity sync. After last error parity.exe has stopped working.

This is my log:

2017-07-19 14:20:00  Starting Parity/v1.6.9-stable-d44b008-20170716/x86_64-windows-msvc/rustc1.18.0
2017-07-19 14:20:00  State DB configuration: fast
2017-07-19 14:20:00  Operating mode: active
2017-07-19 14:20:00  Configured for Kovan using AuthorityRound engine
2017-07-19 14:20:00  Updated conversion rate to Ξ1 = US$230.34 (516834340 wei/gas)
2017-07-19 14:20:05  Public node URL: enode://f99ec5e0ec0ab258c4209b010f33177c8a0976823f596b383b01dcf6a9b815c90fce132065
eb07bd9d2b7febcb60ef4ed8c4da0b5ddb6198f75d4ba442b152ce@127.0.0.1:30303
2017-07-19 14:20:10  Syncing snapshot 0/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-19 14:20:15  Syncing snapshot 4/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-19 14:20:20  Syncing snapshot 8/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-19 14:20:25  Syncing snapshot 12/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-19 14:20:30  Syncing snapshot 16/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-19 14:20:32  Encountered error during block restoration: RlpExpectedToBeData
2017-07-19 14:20:35  Syncing snapshot 19/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
thread 'IO Worker #3' panicked at 'OpenBlock::new only fails if parent state root invalid; state root of best block's header is never invalid; qed: Trie(InvalidStateRoot(24801
55b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2))', src\libcore\result.rs:859
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: BaseThreadInitThunk

**Comment by keorn** [comment]
Separate from the old issue https://github.com/paritytech/parity/issues/4891, but a few additional recent reports there.

**Comment by rphmeier** [comment]
It's best to run with `--no-warp` for now

**Comment by schmidsi** [comment]
I have the same issue on Mac OS X Sierra v10.12.5 (16F73)

With the darwin installer from [Releases](https://github.com/paritytech/parity/releases). Both with 1.6.9 and 1.6.8. Also had the same error with a self-compiled version:

```bash
/Applications/Parity Ethereum.app/Contents/MacOS$ ./parity --chain kovan
Loading config file from /Users/schmidsi/Library/Application Support/io.parity.ethereum/config.toml
2017-07-20 19:27:24  Starting Parity/v1.6.8-beta-c396229-20170608/x86_64-macos/rustc1.17.0
2017-07-20 19:27:24  State DB configuration: fast
2017-07-20 19:27:24  Operating mode: active
2017-07-20 19:27:24  Configured for Kovan using AuthorityRound engine
2017-07-20 19:27:24  Updated conversion rate to Ξ1 = US$225.46 (528021000 wei/gas)
2017-07-20 19:27:25  Public node URL: enode://fd9ca10dc6edd9bd185cc99c737c29f1d4d882bcd8c6369b06cfc1adea85d2e3b049f8f3d2360a881fb11047f2d6f775b6c6eedd401f9ca8fd774fe6b4304d98@192.168.0.19:30303
2017-07-20 19:27:34  Syncing snapshot 3/20        #0    2/ 3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  58 µs
2017-07-20 19:27:39  Syncing snapshot 11/20        #0    2/ 3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  54 µs
2017-07-20 19:27:43  Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 19:27:44  Syncing snapshot 19/20        #0    0/ 3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,  54 µs
thread 'IO Worker #3' panicked at 'OpenBlock::new only fails if parent state root invalid; state root of best block's header is never invalid; qed: Trie(InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2))', src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <ethcore::client::client::Client as ethcore::client::traits::MiningBlockChainClient>::prepare_open_block
  10: ethcore::miner::miner::Miner::prepare_block
  11: <ethcore::miner::miner::Miner as ethcore::miner::MinerService>::update_sealing
  12: <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine>::step
  13: <ethcore::engines::authority_round::TransitionHandler as ethcore_io::IoHandler<()>>::timeout
  14: std::panicking::try::do_call
Abort trap: 6
```

Unfortunately, ```--no-warp``` does not help:

```bash
/Applications/Parity Ethereum.app/Contents/MacOS$ ./parity --chain kovan --no-warp
Loading config file from /Users/schmidsi/Library/Application Support/io.parity.ethereum/config.toml
2017-07-20 19:30:05  Starting Parity/v1.6.8-beta-c396229-20170608/x86_64-macos/rustc1.17.0
2017-07-20 19:30:05  State DB configuration: fast
2017-07-20 19:30:05  Operating mode: active
2017-07-20 19:30:05  Configured for Kovan using AuthorityRound engine
2017-07-20 19:30:06  Updated conversion rate to Ξ1 = US$225.6 (527693300 wei/gas)
2017-07-20 19:30:06  State root not found for block #0 (a3c565fc15c7478862d50ccd6561e3c06b24cc509bf388941c25ea985ce32cb9)
thread 'main' panicked at 'State root of best block header always valid.: InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2)', src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::panicking::default_hook::{{closure}}
   2: std::panicking::default_hook
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: std::panicking::begin_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: ethcore::client::client::Client::state
  10: ethcore::client::client::Client::state_at
  11: <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::nonce
  12: <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::call_contract
  13: ethcore::client::client::Client::new::{{closure}}
  14: ethcore::client::registry::Registry::get_address
  15: <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::registry_address
  16: parity_updater::updater::Updater::poll
  17: parity_updater::updater::Updater::new
  18: parity::run::execute
  19: parity::execute
  20: parity::main_direct
  21: parity::main
  22: std::panicking::try::do_call
Abort trap: 6
```

It only happens on kovan. Homestead is fine.

**Comment by schmidsi** [comment]
Same with docker:

```bash
$ docker run parity/parity:v1.6.9 --chain kovan
2017-07-20 17:49:56 UTC Starting Parity/v1.6.9-stable-d44b008-20170716/x86_64-linux-gnu/rustc1.18.0
2017-07-20 17:49:56 UTC State DB configuration: fast
2017-07-20 17:49:56 UTC Operating mode: active
2017-07-20 17:49:56 UTC Configured for Kovan using AuthorityRound engine
2017-07-20 17:49:57 UTC Updated conversion rate to Ξ1 = US$223.82 (531890000 wei/gas)
2017-07-20 17:50:02 UTC Public node URL: enode://9f7dfd40c1f413eee724950caea773d8aaec92ce88ca1c318816d23cfe3f3b1ad3c7f577c9b6b10148e1fa9d80b8de6c2360d9c429a5074ed8e8a79b07d2087e@172.17.0.2:30303
2017-07-20 17:50:02 UTC Syncing       #0 a3c5…2cb9     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:07 UTC Syncing snapshot 1/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:12 UTC Syncing snapshot 5/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:17 UTC Syncing snapshot 8/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:22 UTC Syncing snapshot 11/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:28 UTC Syncing snapshot 16/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:31 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:50:32 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:50:33 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:50:36 UTC Syncing snapshot 2/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:49 UTC Syncing snapshot 16/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:50:54 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:50:54 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:50:55 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:50:56 UTC Syncing snapshot 0/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:01 UTC Syncing snapshot 6/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:07 UTC Syncing snapshot 13/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:13 UTC Syncing snapshot 18/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:13 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:51:14 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:51:15 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:51:21 UTC Syncing snapshot 7/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:29 UTC Syncing snapshot 15/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:31 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:51:36 UTC Syncing snapshot 5/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:42 UTC Syncing snapshot 13/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:47 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:51:47 UTC Syncing snapshot 18/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:51:48 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:51:57 UTC Syncing snapshot 11/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:02 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:52:02 UTC Encountered error during state restoration: IO error: /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/000040.log: No such file or directory
2017-07-20 17:52:02 UTC Encountered error during state restoration: IO error: /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/000040.log: No such file or directory
2017-07-20 17:52:02 UTC Encountered error during state restoration: IO error: /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/000040.log: No such file or directory
2017-07-20 17:52:06 UTC Syncing snapshot 4/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:11 UTC Syncing snapshot 10/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:17 UTC Syncing snapshot 17/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:18 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:52:18 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:52:18 UTC Encountered error during state restoration: IO error: /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/000044.log: No such file or directory
2017-07-20 17:52:26 UTC Syncing snapshot 9/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:33 UTC Syncing snapshot 16/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:35 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:52:42 UTC Syncing snapshot 8/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:47 UTC Syncing snapshot 13/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:52:52 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:52:52 UTC Syncing       #0 a3c5…2cb9     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:02 UTC Syncing snapshot 6/20        #0    3/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:08 UTC Syncing snapshot 11/20        #0    4/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:13 UTC Syncing snapshot 15/20        #0    4/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:18 UTC Encountered error during block restoration: RlpExpectedToBeData
2017-07-20 17:53:19 UTC Failed to initialize snapshot restoration: IO error: lock /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98/snapshot/restoration/db/LOCK: No locks available
2017-07-20 17:53:22 UTC Syncing snapshot 0/20        #0    4/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:27 UTC Syncing snapshot 6/20        #0    4/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:33 UTC Syncing snapshot 11/20        #0    4/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:41 UTC Syncing snapshot 17/20        #0    4/25 peers     7 KiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-07-20 17:53:41 UTC Encountered error during block restoration: RlpExpectedToBeData
thread 'IO Worker #3' panicked at 'OpenBlock::new only fails if parent state root invalid; state root of best block's header is never invalid; qed: Trie(InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2))', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
```
