### ISSUE TITLE
Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:537

### ISSUE THREAD

**Issue by BatLesStakes** [paritytech/parity#6239]
Hey, all is in the title

I got this error when I launch Parity and a pool software at the same time : 

`stack backtrace:
   0:     0x55f790a2939c - backtrace::backtrace::trace::h18b17b72e62d3e01

Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:537

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted`

Where can it come from ?

Thanks

**Comment by rphmeier** [comment]
What Parity version are you running?
@vurich could it be related to your recent changes?

**Comment by BatLesStakes** [comment]
I'm using the latest one, maybe that's the problem

Le 5 août 2017 23:37, "Robert Habermeier" <notifications@github.com> a
écrit :

**Comment by antoinemineau** [comment]
I am working with @BatLesStakes on the project. We used the latest master branch commit to compile and we had the error above.

By using an oldest version, this error doesn't seem to appear anymore, we have a few crash of parity but it is more stable.

I am guessing the master branch is unstable.

**Comment by 5chdn** [comment]
> I am guessing the master branch is unstable.

Yes, have a look at the [beta](https://github.com/paritytech/parity/tree/beta) and [stable](https://github.com/paritytech/parity/tree/stable) branches.

**Comment by Vurich** [comment]
I removed a lot of uses of unsafe indexing, either I also removed a check that we were doing or we had some undefined behaviour that is now being caught by the bounds check.

**Comment by Vurich** [comment]
Doesn't look related:

```rust
impl Header {
	/// Get the none field of the header.
	pub fn nonce(&self) -> H64 {
		rlp::decode(&self.seal()[1])
	}

	// ...
}
```

`seal` is returning an empty array. We actually have a `Default` implementation that returns a `Header` with an empty `seal`. Maybe it's a good idea to not have our default header instantly panic if you try to do anything with it. Returning an `Option` would be a good start. If we expect `nonce` and `mix_hash` to always exist, we could make it impossible to construct `Header` without them (ideally by using the type system, of course, but just removing the `Default` impl would work for me too).

**Comment by 5chdn** [comment]
Keeps to get triggered in many different situations #6289 #6381 #6385

**Comment by stone212** [comment]
If you would recommend using an older version temporarily, which version?  I assumed that building the current release from source was considered most "stable" but I will install another version if you recommend it.  Perhaps an older binary from this page: https://github.com/paritytech/parity/releases

What version have you found success with?  Thank you.

**Comment by debris** [comment]
thanks to @kondratovich I reproduced the issue

curl to parity several times asking for pending block

```
curl --data '{"method":"eth_getBlockByNumber","params":["pending",false],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

debug stack trace:

```
./target/debug/parity --stratum                                                                                                                                           134 ↵
2017-08-27 11:44:04  Starting Parity/v1.8.0-unstable-7246c9c-20170826/x86_64-macos/rustc1.19.0
2017-08-27 11:44:04  Keys path /Users/marek/Library/Application Support/io.parity.ethereum/keys/Foundation
2017-08-27 11:44:04  DB path /Users/marek/Library/Application Support/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-08-27 11:44:04  Path to dapps /Users/marek/Library/Application Support/io.parity.ethereum/dapps
2017-08-27 11:44:04  State DB configuration: fast
2017-08-27 11:44:04  Operating mode: active
2017-08-27 11:44:04  Configured for Foundation using Ethash engine
2017-08-27 11:44:04  Updated conversion rate to Ξ1 = US$334.53 (355865300 wei/gas)
2017-08-27 11:44:09  Removed existing file '/Users/marek/Library/Application Support/io.parity.ethereum/jsonrpc.ipc'.
2017-08-27 11:44:14  Public node URL: enode://3e57cfb7a1c7391eefb614f655047c9790aa67f21ad250a076878eb4db635d2170a2dc7da0920a2d82a48c7bc8ee54278112e324fa45a9070f4a228952af0444@192.168.0.11:30303
2017-08-27 11:44:28  Imported #4208971 62a3…5705 (115 txs, 6.65 Mgas, 3524.75 ms, 21.23 KiB) + another 3 block(s) containing 340 tx(s)

====================

stack backtrace:
   0:        0x10c7f47e4 - backtrace::backtrace::trace<closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/backtrace/mod.rs:42
   1:        0x10c7f4b8f - backtrace::capture::Backtrace::new::h92218407e8745e0e
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.2/src/capture.rs:64
   2:        0x109b3f7e3 - panic_hook::panic_hook
                        at panic_hook/src/lib.rs:53
   3:        0x109b3dcf8 - core::ops::Fn::call<fn(&std::panicking::PanicInfo),(&std::panicking::PanicInfo)>
                        at /Users/travis/build/rust-lang/rust/src/libcore/ops.rs:2588
   4:        0x10c8c55e6 - std::panicking::rust_panic_with_hook::h8b9b25777425677b
                        at src/libstd/panicking.rs:550
   5:        0x10c8c5444 - std::panicking::begin_panic<collections::string::String>
                        at src/libstd/panicking.rs:511
   6:        0x10c8c53b2 - std::panicking::begin_panic_fmt::haf8695bfb6c52436
                        at src/libstd/panicking.rs:495
   7:        0x10c8c5317 - rust_begin_unwind
                        at src/libstd/panicking.rs:471
   8:        0x10c8ecd50 - core::panicking::panic_fmt::hfedd6515bcee8bb1
                        at src/libcore/panicking.rs:69
   9:        0x10c8eccc8 - core::panicking::panic_bounds_check::h7e54553d1bd69142
                        at src/libcore/panicking.rs:56
  10:        0x10b180223 - ethcore::ethereum::ethash::_$LT$impl$u20$ethcore..header..Header$GT$::nonce::hf0e864a405fd28d3
                        at ethcore/src/ethereum/ethash.rs:540
  11:        0x10b178fa6 - ethcore::ethereum::ethash::_$LT$impl$u20$ethcore..engines..Engine$u20$for$u20$alloc..arc..Arc$LT$ethcore..ethereum..ethash..Ethash$GT$$GT$::extra_info::ha71267ccdbe75b43
                        at ethcore/src/ethereum/ethash.rs:190
  12:        0x10b12a1d4 - ethcore::client::client::{{impl}}::block_extra_info::{{closure}}
                        at ethcore/src/client/client.rs:1729
  13:        0x10aaa2315 - core::option::{{impl}}::map<ethcore::encoded::Header,collections::btree::map::BTreeMap<collections::string::String, collections::string::String>,closure>
                        at /Users/travis/build/rust-lang/rust/src/libcore/option.rs:398
  14:        0x10b12a0cf - _$LT$ethcore..client..client..Client$u20$as$u20$ethcore..client..traits..BlockChainClient$GT$::block_extra_info::h6cf8d6a892af6cf4
                        at ethcore/src/client/client.rs:1728
  15:        0x10994af71 - parity_rpc::v1::impls::eth::{{impl}}::block<ethcore::client::client::Client,SnapshotService,SyncProvider,ethcore::miner::miner::Miner,ethcore::miner::external::ExternalMiner>
                        at /Users/marek/projects/ethcore/parity/rpc/src/v1/impls/eth.rs:176
  16:        0x108ef6d31 - parity_rpc::v1::impls::eth::{{impl}}::block_by_number<ethcore::client::client::Client,SnapshotService,SyncProvider,ethcore::miner::miner::Miner,ethcore::miner::external::ExternalMiner>
                        at /Users/marek/projects/ethcore/parity/rpc/src/v1/impls/eth.rs:466
  17:        0x109006927 - jsonrpc_macros::auto_args::{{impl}}::wrap_rpc<parity_rpc::v1::impls::eth::EthClient<ethcore::client::client::Client, SnapshotService, SyncProvider, ethcore::miner::miner::Miner, ethcore::miner::external::ExternalMiner>,core::option::Option<parity_rpc::v1::types::block::Rich<parity_rpc::v1::types::block::Block>>,parity_rpc::v1::types::block_number::BlockNumber,bool>
                        at /Users/marek/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/b549078/macros/src/auto_args.rs:381
  18:        0x108d6bc53 - parity_rpc::v1::traits::eth::Eth::to_delegate::{{closure}}<parity_rpc::v1::impls::eth::EthClient<ethcore::client::client::Client, SnapshotService, SyncProvider, ethcore::miner::miner::Miner, ethcore::miner::external::ExternalMiner>>
                        at /Users/marek/projects/ethcore/parity/<build_rpc_trait macros>:65
  19:        0x108ea307f - jsonrpc_macros::delegates::{{impl}}::call<parity_rpc::v1::impls::eth::EthClient<ethcore::client::client::Client, SnapshotService, SyncProvider, ethcore::miner::miner::Miner, ethcore::miner::external::ExternalMiner>,parity_rpc::v1::metadata::Metadata,closure>
                        at /Users/marek/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/b549078/macros/src/delegates.rs:43
  20:        0x109598730 - jsonrpc_core::io::{{impl}}::handle_call::{{closure}}::{{closure}}<parity_rpc::v1::metadata::Metadata,parity_rpc::v1::informant::Middleware<parity_rpc::v1::informant::ClientNotifier>>
                        at /Users/marek/.cargo/git/checkouts/jsonrpc-22a65938f7d26b63/b549078/core/src/io.rs:223
  21:        0x109579300 - futures::future::lazy::{{impl}}::get<closure,alloc::boxed::Box<Future>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/lazy.rs:64
  22:        0x1098f9c3a - futures::future::lazy::{{impl}}::poll<closure,alloc::boxed::Box<Future>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/lazy.rs:82
  23:        0x1096ab01e - futures::future::chain::{{impl}}::poll<futures::future::lazy::Lazy<closure, alloc::boxed::Box<Future>>,futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>,closure,closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/chain.rs:26
  24:        0x1099c5a53 - futures::future::then::{{impl}}::poll<futures::future::lazy::Lazy<closure, alloc::boxed::Box<Future>>,futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>,closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/then.rs:32
  25:        0x109717666 - futures::future::{{impl}}::poll<Future>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/mod.rs:106
  26:        0x109943f45 - futures::future::either::{{impl}}::poll<alloc::boxed::Box<Future>,futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/either.rs:35
  27:        0x1098e6166 - futures::future::map::{{impl}}::poll<core::option::Option<jsonrpc_core::types::response::Response>,futures::future::either::Either<alloc::boxed::Box<Future>, futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>>,closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/map.rs:30
  28:        0x109943ec5 - futures::future::either::{{impl}}::poll<futures::future::map::Map<futures::future::either::Either<alloc::boxed::Box<Future>, futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>>, closure>,futures::future::map::Map<futures::future::join_all::JoinAll<collections::vec::Vec<futures::future::either::Either<alloc::boxed::Box<Future>, futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>>>>, closure>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/either.rs:35
  29:        0x1098e41e6 - futures::future::map::{{impl}}::poll<core::option::Option<jsonrpc_core::types::response::Response>,futures::future::either::Either<futures::future::map::Map<futures::future::either::Either<alloc::boxed::Box<Future>, futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>>, closure>, futures::future::map::Map<futures::future::join_all::JoinAll<collections::vec::Vec<futures::future::either::Either<alloc::boxed::Box<Future>, futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Output>, ()>>>>, closure>>,closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/map.rs:30
  30:        0x109717616 - futures::future::{{impl}}::poll<Future>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/mod.rs:106
  31:        0x109943d60 - futures::future::either::{{impl}}::poll<futures_cpupool::CpuFuture<core::option::Option<jsonrpc_core::types::response::Response>, ()>,alloc::boxed::Box<Future>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/either.rs:36
  32:        0x109943de0 - futures::future::either::{{impl}}::poll<futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Response>, ()>,futures::future::either::Either<futures_cpupool::CpuFuture<core::option::Option<jsonrpc_core::types::response::Response>, ()>, alloc::boxed::Box<Future>>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/either.rs:36
  33:        0x1098e7a16 - futures::future::map::{{impl}}::poll<core::option::Option<collections::string::String>,futures::future::either::Either<futures::future::result_::FutureResult<core::option::Option<jsonrpc_core::types::response::Response>, ()>, futures::future::either::Either<futures_cpupool::CpuFuture<core::option::Option<jsonrpc_core::types::response::Response>, ()>, alloc::boxed::Box<Future>>>,closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/map.rs:30
  34:        0x109717ca6 - futures::future::{{impl}}::poll<Future>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/mod.rs:106
  35:        0x1098e5c35 - futures::future::map::{{impl}}::poll<(),alloc::boxed::Box<Future>,closure>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/map.rs:30
  36:        0x10c59d0df - futures::future::{{impl}}::poll<Future>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/future/mod.rs:106
  37:        0x10c58a79c - futures::task_impl::{{impl}}::poll_future::{{closure}}<alloc::boxed::Box<Future>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:337
  38:        0x10c58aacf - futures::task_impl::{{impl}}::enter::{{closure}}<alloc::boxed::Box<Future>,closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:484
  39:        0x10c59ea15 - futures::task_impl::set::{{closure}}<closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:61
  40:        0x10c58ba64 - std::thread::local::{{impl}}::with<core::cell::Cell<*const futures::task_impl::BorrowedTask>,closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/local.rs:265
  41:        0x10c59e89d - futures::task_impl::set<closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:54
  42:        0x10c58a91d - futures::task_impl::{{impl}}::enter<alloc::boxed::Box<Future>,closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:484
  43:        0x10c58a752 - futures::task_impl::{{impl}}::poll_future<alloc::boxed::Box<Future>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.11/src/task_impl/mod.rs:337
  44:        0x10c5a93c6 - tokio_core::reactor::{{impl}}::dispatch_task::{{closure}}
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:366
  45:        0x10c586419 - scoped_tls::{{impl}}::set<tokio_core::reactor::Core,closure,core::result::Result<futures::poll::Async<()>, ()>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-0.1.0/src/lib.rs:135
  46:        0x10c5a90df - tokio_core::reactor::{{impl}}::dispatch_task
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:366
  47:        0x10c5a8895 - tokio_core::reactor::{{impl}}::dispatch
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:324
  48:        0x10c5a84a8 - tokio_core::reactor::Core::poll::h43952d499d068722
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:312
  49:        0x10a5a01de - tokio_core::reactor::{{impl}}::run<futures::future::select::Select<futures::future::empty::Empty<(), futures::sync::oneshot::Canceled>, futures::sync::oneshot::Receiver<()>>>
                        at /Users/marek/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.6/src/reactor/mod.rs:249
  50:        0x10a5c5d1a - parity_reactor::{{impl}}::spawn::{{closure}}
                        at util/reactor/src/lib.rs:45
  51:        0x10a5a543a - std::sys_common::backtrace::__rust_begin_short_backtrace<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  52:        0x10a5a6fea - std::thread::{{impl}}::spawn::{{closure}}::{{closure}}<closure,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:364
  53:        0x10a5c4e9a - std::panic::{{impl}}::call_once<(),closure>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:296
  54:        0x10a5a72c7 - std::panicking::try::do_call<std::panic::AssertUnwindSafe<closure>,()>
                        at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:454

Thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 1', ethcore/src/ethereum/ethash.rs:540

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

[1]    19110 abort      ./target/debug/parity --stratum
```

**Comment by debris** [comment]
I think the bug was introduced in 2d7a7867caf7eedc3e0efb1c1f8243aeb517aa3f

**Comment by debris** [comment]
As can be seen in the pr, client is now returning `block`, `block_header` and `block_body` for `BlockId::Pending`. All returned headers have invalid (empty) seals. This leads to various types of crushes

As a temporary solution, I suggest reverting the part of pr #6195 which modifies client.rs.

As a long term solution, I suggest refactor of header, block and sealing to give compile time guarantees that this type of bugs does not occur

**Comment by debris** [comment]
After talking with @tomusdrw we decided, that it's enough for temporary fix to change only `extra_info` method

**Comment by stone212** [comment]
@debris Does this mean that the error is gone with the build-from-source version of Parity?

**Comment by debris** [comment]
yes
