### ISSUE TITLE
Windows 10 Parity Hang before Launch

### ISSUE THREAD

**Issue by cloudzombie** [paritytech/parity#6416]
> I'm running:
>
> - **Parity version**: 1.7.0
> - **Operating system**: Windows 10
> - **And installed**:  from source using powershell

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I installed from source using git pull in powershell, I get as far as it initializes and seems like its starting to sync, then hangs. I am just trying to get parity back to working on my machine. At this point I cannot get it to even fully launch and sync a chain. 

The output is as follows
```
stack backtrace:
   0:     0x7ff618763f39 - panic_hook::set::h4e9d48afd79ba8f1
   1:     0x7ff618764263 - backtrace::capture::Backtrace::new::hb66f705987bf244f
   2:     0x7ff6187635c4 - panic_hook::set::h4e9d48afd79ba8f1
   3:     0x7ff61907c850 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:550
   4:     0x7ff61907c6e9 - std::panicking::begin_panic<collections::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:511
   5:     0x7ff61907c5f2 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:495
   6:     0x7ff61907c56a - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:471
   7:     0x7ff619086938 - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:69
   8:     0x7ff618a9a953 - <bincode::internal::ErrorKind as core::fmt::Display>::fmt::h9ea68df87c12936e
   9:     0x7ff618b6bf96 - ethcore::client::client::Client::state::h673128a31e1a3a0b
  10:     0x7ff618b6b495 - ethcore::client::client::Client::state_at::h6dc56e07d8b04402
  11:     0x7ff618b7d2c3 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::nonce::had14a1b395c1b8d8
  12:     0x7ff618b6ef53 - ethcore::client::client::Client::tick::h5b4dbf6bfa0920ac
  13:     0x7ff618b8bc34 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::call_contract::h2ac0bdea7f525fb6
  14:     0x7ff618b8d104 - <ethcore::client::client::Client as ethcore::client::traits::BlockChainClient>::registry_address::h1aad7fb7afeaf3e8
  15:     0x7ff6188cbabc - parity_updater::updater::Updater::new::h09bf0402ae2f6fd0
  16:     0x7ff6188c9568 - parity_updater::updater::Updater::new::h09bf0402ae2f6fd0
  17:     0x7ff6186a8c94 - <schannel::cert_store::CertStore as schannel::Inner<*mut std::os::raw::c_void>>::as_inner::h34e4c98a44ee6b08
  18:     0x7ff6186c2b6c - <schannel::cert_store::CertStore as schannel::Inner<*mut std::os::raw::c_void>>::as_inner::h34e4c98a44ee6b08
  19:     0x7ff6186c796a - <schannel::cert_store::CertStore as schannel::Inner<*mut std::os::raw::c_void>>::as_inner::h34e4c98a44ee6b08
  20:     0x7ff6186cb176 - <schannel::cert_store::CertStore as schannel::Inner<*mut std::os::raw::c_void>>::as_inner::h34e4c98a44ee6b08
  21:     0x7ff61907e202 - panic_abort::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_abort\lib.rs:42
  22:     0x7ff61907cfdf - std::rt::lang_start
                        at C:\projects\rust\src\libstd\rt.rs:52
  23:     0x7ff619278af9 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  24:     0x7ffc66112774 - BaseThreadInitThunk

Thread 'main' panicked at 'State root of best block header always valid.: InvalidStateRoot(2480155b48a1cea17d67dbfdfaafe821c1d19cdd478c5358e8ec56dec24502b2)', src\libcore\result.rs:860
```

**Comment by 5chdn** [comment]
Does this also happen with latest beta 1.7.2? Can you share the full logs after launching parity?

**Comment by folsen** [comment]
Reopen if reproducible after `parity db kill`
