### ISSUE TITLE
snap crashes while initial syncing

### ISSUE THREAD

**Issue by chymian** [paritytech/parity#6434]
Dear maintainers,
The parity-snap crashed while initial syncing the blockchain after having downloaded:
```
date; du ~/snap/parity/*
Fr 1. Sep 16:08:12 CEST 2017
4,2G    /home/guenter/snap/parity/2723
0       /home/guenter/snap/parity/common
4,0K    /home/guenter/snap/parity/current
4,2G    insgesamt
```
The path ```/home/guenter/snap/parity/``` is a crossmounted btrfs-subvolume, no compression

## Running:
* in a KVM
* Host & VM: debian stretch
* VM:
```
snap --version
snap    2.26.14
snapd   2.26.14
series  16
debian  9
kernel  4.11.0-0.bpo.1-amd64

snap info parity
name:      parity
summary:   "Fast, light, robust Ethereum implementation"
publisher: devops-parity
description: |
...
commands:
  - parity
tracking:    edge
installed:   0+git.47f7366 (2723) 12MB -
refreshed:   2017-09-01 13:00:07 +0200 CEST
channels:
  stable:    –
  candidate: –
  beta:      –
  edge:      0+git.56f46ed (2729) 12MB -
```
### initial run
```
....
2017-09-01 15:55:59  Syncing #4225644 057f…5a1c     0 blk/s    6 tx/s   1 Mgas/s      0+  684 Qed  #4226332    6/25 peers      4 MiB chain   80 MiB db   80 MiB queue    8 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-01 15:56:09  Syncing #4225648 ce8a…1da9     0 blk/s   36 tx/s   2 Mgas/s      0+  680 Qed  #4226332    6/25 peers      4 MiB chain   79 MiB db   80 MiB queue    8 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-01 15:56:19  Syncing #4225650 d088…cf66     0 blk/s   34 tx/s   1 Mgas/s      0+  680 Qed  #4226332    6/25 peers      4 MiB chain   80 MiB db   80 MiB queue    8 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

stack backtrace:
   0:     0x55ad2b329bcc - backtrace::backtrace::trace::h9b9a5fb45660e72d

Thread 'IO Worker #3' panicked at 'Low-level database error. Some issue with your hard disk?: "Corruption: Snappy not supported or corrupted Snappy compressed block contents"', /checkout/src/libcore/result.rs:860
```
### restart:
```
time ssh -X trust1 /snap/bin/parity --geth  --pruning fast --whisper 
2017-09-01 15:58:46  Starting Parity/v1.8.0-unstable-47f7366-20170831/x86_64-linux-gnu/rustc1.20.0
2017-09-01 15:58:46  Keys path /home/guenter/snap/parity/2723/.parity/keys/Foundation
2017-09-01 15:58:46  DB path /home/guenter/snap/parity/2723/.parity/chains/ethereum/db/906a34e69aec8c0d
2017-09-01 15:58:46  Path to dapps /home/guenter/snap/parity/2723/.parity/dapps
2017-09-01 15:58:46  State DB configuration: fast
2017-09-01 15:58:46  Operating mode: active
2017-09-01 15:58:47  Configured for Foundation using Ethash engine
2017-09-01 15:58:47  Updated conversion rate to Ξ1 = US$393.73 (302358530 wei/gas)
2017-09-01 15:58:50  Removed existing file '/home/guenter/snap/parity/2723/.ethereum/geth.ipc'.
2017-09-01 15:58:55  Public node URL: enode://427d9caea60c0d84dd63300563de9e88d78429ae8f7b614bfe27067b190e8486d783994e9db9c4ea791b51c2cba9003a3e0b6b13c3bddc2253e55f737205917b@192.168.33.173:30303
2017-09-01 15:59:01  Syncing #4225648 ce8a…1da9     0 blk/s    0 tx/s   0 Mgas/s     59+    0 Qed  #4225711    7/25 peers     36 KiB chain   65 MiB db    3 MiB queue  488 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

stack backtrace:
   0:     0x55b6ace43bcc - backtrace::backtrace::trace::h9b9a5fb45660e72d

Thread 'Verifier #0' panicked at 'Low-level database error. Some issue with your hard disk?: "Corruption: Snappy not supported or corrupted Snappy compressed block contents"', /checkout/src/libcore/result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

done!
```

There was nothing in the systemd-journal.
After rebooting the VM and an additional btrfsck on the crossmounted Volume (no errors detected),
partity started normal and continued the download of THE CHAIN.

IMHO:
it might have been a btrfs-corruption, with had been corrected during systemstartup, but then, there should have been a syslog-entry…
the crossmounted volume is a LVM2-lv on the host, newly created.

cheers
guenter

---

**Comment by 5chdn** [comment]
There is probably not much we can do right now for you. The panic indicates there is something wrong writing to the disk, _probably_ a corruption. If this is corrected somehow after the system restart, and it does not appear again, you are fine.

Please report back if this issue persists.

**Comment by chymian** [comment]
I had the issue 5 or 6 times more and it finally corrupted the db. I added to https://github.com/paritytech/parity/issues/5474.
what is the preferred version: docker, source install, snap?

**Comment by 5chdn** [comment]
Whatever _you_ prefer :)
