### ISSUE TITLE
seg fault after synching snapshot

### ISSUE THREAD

**Issue by julian1** [paritytech/parity#6535]
same behavior on two different digital ocean servers. restart and it crashes again

**I'm running:**
 
```
$ parity -v
Parity
  version Parity/v1.6.10-unstable-1a5b17626-20170721/x86_64-linux-gnu/rustc1.20.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann
```

**Operating system**: 
```
$ uname -a
Linux parity-test 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux
```

**Compiled rom source:**

```
$ rustc --version
rustc 1.20.0 (f3d6973f4 2017-08-27)
```

**actual behavor:**
```
$ parity -d data
...

2017-09-18 00:20:14 UTC Syncing snapshot 325/341        #0   30/50 peers     3 MiB db    7 KiB chain  0 bytes queue   19 KiB sync  RPC:  0 conn,  0 req/s, 180 µs
2017-09-18 00:20:19 UTC Syncing snapshot 333/341        #0   30/50 peers     3 MiB db    7 KiB chain  0 bytes queue   19 KiB sync  RPC:  0 conn,  0 req/s, 180 µs
2017-09-18 00:20:25 UTC Syncing snapshot 341/341        #0   30/50 peers     1 KiB db   17 KiB chain  0 bytes queue   19 KiB sync  RPC:  0 conn,  0 req/s, 180 µs
2017-09-18 00:20:34 UTC Syncing #4285002 4179…e30f     0 blk/s   17 tx/s   1 Mgas/s    250+    1 Qed  #4285251   20/25 peers     1 MiB db  930 KiB chain    7 MiB queue   27 MiB sync  RPC:  0 conn,  0 req/s, 180 µs
2017-09-18 00:20:39 UTC Syncing #4285014 0f63…0ffe     2 blk/s  137 tx/s  10 Mgas/s    478+    9 Qed  #4285506   17/25 peers     9 MiB db    1 MiB chain   13 MiB queue   31 MiB sync  RPC:  0 conn,  0 req/s, 180 µs
Segmentation fault
```
---

Edit. with gdb on release binary,

```
iB queue   23 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 01:00:49 UTC Imported #4285254 d697…a0d4 (4 txs, 0.09 Mgas, 82.39 ms, 0.96 KiB) + another 1 block(s) containing 37 tx(s)
2017-09-18 01:01:14 UTC     #36760   12/25 peers   189 MiB db    4 MiB chain  0 bytes queue   10 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 01:01:24 UTC Syncing #4285304 4bd3…11fc     5 blk/s  323 tx/s  26 Mgas/s     75+    0 Qed  #4285381   11/25 peers   190 MiB db    6 MiB chain    2 MiB queue   10 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

Thread 22 "Verifier #1" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe75fe700 (LWP 8025)]
malloc_usable_size (ptr=0x8) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h:743
(gdb) 
(gdb) bt
#0  malloc_usable_size (ptr=0x8) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h:743
#1  0x0000555555ef345e in _$LT$ethcore..verification..verification..PreverifiedBlock$u20$as$u20$heapsize..HeapSizeOf$GT$::heap_size_of_children::h624b2bb9fed91
e2e ()
#2  0x0000555555ccc2bb in std::sys_common::backtrace::__rust_begin_short_backtrace::hcf35893122597e65 ()
#3  0x0000555555cd1937 in std::panicking::try::do_call::h7a02d15905263d17 ()
#4  0x0000555556326ffc in panic_abort::__rust_maybe_catch_panic () at /checkout/src/libpanic_abort/lib.rs:40
#5  0x0000555555d60d42 in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h0fb5f350b151e762 ()
#6  0x000055555631f3dc in alloc::boxed::{{impl}}::call_once<(),()> () at /checkout/src/liballoc/boxed.rs:661
#7  std::sys_common::thread::start_thread () at /checkout/src/libstd/sys_common/thread.rs:21
#8  std::sys::imp::thread::{{impl}}::new::thread_start () at /checkout/src/libstd/sys/unix/thread.rs:84
#9  0x00007ffff6793494 in start_thread (arg=0x7fffe75fe700) at pthread_create.c:333
#10 0x00007ffff7b22aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

```

**Comment by julian1** [comment]
probably a duplicate, https://github.com/paritytech/parity/issues/6446. Is this a known bug in the compiler or parity?

**Comment by julian1** [comment]
reopening, still present when parity is compiled with rust 1.19.0 as indicated in the [readme](https://github.com/paritytech/parity/blob/master/README.md)


```
$ parity --version
Parity
  version Parity/v1.6.10-unstable-1a5b17626-20170721/x86_64-linux-gnu/rustc1.19.0
Copyright 2015, 2016, 2017 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
...
```

datadir deleted and restarted,
```
2017-09-18 04:44:11 UTC Syncing snapshot 316/341        #0   22/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 04:44:16 UTC Syncing snapshot 322/341        #0   22/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 04:44:21 UTC Syncing snapshot 334/341        #0   22/25 peers     3 MiB db    7 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 04:44:27 UTC Syncing snapshot 341/341        #0   22/25 peers     1 KiB db   17 KiB chain  0 bytes queue   10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 04:44:36 UTC Syncing #4285021 b770…b7c7     2 blk/s  127 tx/s  10 Mgas/s    231+    1 Qed  #4285254   22/25 peers    14 MiB db  491 KiB chain    6 MiB queue   29 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-09-18 04:44:47 UTC Syncing #4285080 82fc…246b     6 blk/s  448 tx/s  30 Mgas/s    680+    0 Qed  #4285762   20/25 peers    58 MiB db    1 MiB chain   17 MiB queue   41 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

Thread 21 "Verifier #0" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe7bff700 (LWP 13230)]
malloc_usable_size (ptr=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h:743
743     /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h: No such file or directory.
(gdb) bt
#0  malloc_usable_size (ptr=<optimized out>) at /checkout/src/liballoc_jemalloc/../jemalloc/include/jemalloc/internal/arena.h:743
#1  0x0000555555ed4aa3 in _$LT$ethcore..verification..verification..PreverifiedBlock$u20$as$u20$heapsize..HeapSizeOf$GT$::heap_size_of_children::h9a5791a94c684248 ()
#2  0x0000555555cb44f0 in std::sys_common::backtrace::__rust_begin_short_backtrace::h0a6a465fc841cf43 ()
#3  0x0000555555cbc647 in std::panicking::try::do_call::h89d5a09d235002b8 ()
#4  0x00005555562ee9cc in panic_abort::__rust_maybe_catch_panic () at /checkout/src/libpanic_abort/lib.rs:40
#5  0x0000555555d3e1fe in _$LT$F$u20$as$u20$alloc..boxed..FnBox$LT$A$GT$$GT$::call_box::h19144b50cd444028 ()
#6  0x00005555562e6c66 in alloc::boxed::{{impl}}::call_once<(),()> () at /checkout/src/liballoc/boxed.rs:658
#7  std::sys_common::thread::start_thread () at /checkout/src/libstd/sys_common/thread.rs:21
#8  std::sys::imp::thread::{{impl}}::new::thread_start () at /checkout/src/libstd/sys/unix/thread.rs:84
#9  0x00007ffff6793494 in start_thread (arg=0x7fffe7bff700) at pthread_create.c:333
#10 0x00007ffff7b22aff in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97
(gdb)
```

**Comment by julian1** [comment]
ok, so 1.18.0 does work.

**Comment by 5chdn** [comment]
Yes, stable requires 1.18.0
