### ISSUE TITLE
parity.js : unable to properly deploy a contract

### ISSUE THREAD

**Issue by travs** [paritytech/parity#6536]
I'm running:
- **Parity version**: Parity/v1.8.0-unstable-b731ccea1-20170903/x86_64-linux-gnu/rustc1.19.0
- **Operating system**:  Linux
- **And installed**: via `pacman -S parity-git`
- **parity.js** installed via `npm i @parity/parity.js`

---

I want to deploy a small contract using `parity.js`, but I ran into a snag.
Perhaps I am using the library incorrectly?

What I tried:
```js
// adapted from the README.md
const Api = require('@parity/parity.js').Api;
const transport = new Api.Transport.Http('http://localhost:8545');
const api = new Api(transport);
const abi = [{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}] // from a small contract
const bcode = '6060604 ... a0029' // large bytecode string
const contract = new api.newContract(abi);
contract.deploy({data: bcode});
```

Expected result: Contract deployed on Kovan network.

Actual result:

```
TypeError: Cannot read property 'estimateGas' of undefined
    at t.value (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:101529)
    at t.value (/home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:101842)
    at repl:1:10
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:440:10)
    at emitOne (events.js:120:20)
    at REPLServer.emit (events.js:210:7)
```

Is it possible that this arises from [this function](https://github.com/paritytech/parity/blob/master/js/src/api/contract/contract.js#L100-L108)?

Investigating manually, it seems like `contract._api` is undefined, so maybe it was not set in the constructor.

**Comment by travs** [comment]
*Addendum*:

Please let me know if this is a separate issue, and I will create a new one. 
After running the code above, I set the `_api` manually, and get another error:

Further input:

```js
... // continue from above
contract._api = api // "api" previously defined
contract.deploy({data: bcode})
```

Output:

```
Promise {              
  <pending>,           
  domain:              
   Domain {            
     domain: null,     
     _events: { error: [Function: debugDomainError] },                                         
     _eventsCount: 1,  
     _maxListeners: undefined,                 
     members: [] } }   

parity_checkRequest(["0x76161b35c213a8ce6d9073f6ece2be7fc5ce31ad9cf910670788811df4925a46"]): -32042: Request not found.                     
pollMethod { e: parity_checkRequest: -32042: Request not found.                                
    at /home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:161621            
    at <anonymous>     
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)                       
  code: -32042,        
  type: 'REQUEST_NOT_FOUND',                   
  method: 'parity_checkRequest',               
  text: 'Request not found.' }                 
(node:15338) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): e: parity_checkRequest: -32042: Request not found.
```

The promise is rejected with "request not found", but the transaction [appears to have succeeded](https://kovan.etherscan.io/tx/0x76161b35c213a8ce6d9073f6ece2be7fc5ce31ad9cf910670788811df4925a46).

I am running parity as an unlocked node with the following options:
```sh
ACCOUNT_LIQPROV='0x00360d2b7D240Ec0643B6D819ba81A09e40E5bCd'

parity \
  --chain kovan \
  --author $ACCOUNT_LIQPROV \
  --unlock $ACCOUNT_LIQPROV \
  --password ~/prg/keys/kovan/account_liqprov \
  --rpcport 8545 \
  --force-ui
```

**Comment by travs** [comment]
this was a small error in the docs, which #6539 should address.
Opening my comment as a separate issue

**Comment by 5chdn** [comment]
Tests failing https://gitlab.parity.io/parity/parity/-/jobs/65193

```
  1) mobx/HardwareStore background polling scans when timer elapsed:
     TypeError: this._api.parity.lockedHardwareAccountsInfo is not a function
      at HardwareStore.scanTrezor (src/mobx/hardwareStore.js:67:8)
      at HardwareStore.scan (src/mobx/hardwareStore.js:138:10)
      at Function.invoke (node_modules/sinon/lib/sinon/spy.js:176:59)
      at HardwareStore.proxy (node_modules/sinon/lib/sinon/spy.js:85:30)
      at src/mobx/hardwareStore.js:61:12
      at callTimer (node_modules/lolex/src/lolex.js:246:28)
      at Object.tick (node_modules/lolex/src/lolex.js:434:25)
      at Context.<anonymous> (src/mobx/hardwareStore.spec.js:116:13)

  2) mobx/HardwareStore operations scan "before each" hook for "calls scanLedger":
     TypeError: this._api.parity.lockedHardwareAccountsInfo is not a function
      at HardwareStore.scanTrezor (src/mobx/hardwareStore.js:67:8)
      at HardwareStore.scan (src/mobx/hardwareStore.js:138:10)
      at Context.<anonymous> (src/mobx/hardwareStore.spec.js:210:22)
```

Probably related.

**Comment by travs** [comment]
Not sure why this build is failing since I changed just one word in the readme.
I have moved the proposed change over [here](https://github.com/paritytech/parity.js/pull/3), so we can close this and the PR on this repo
