### ISSUE TITLE
Parity.js cannot deploy contracts from an unlocked node

### ISSUE THREAD

**Issue by travs** [paritytech/parity#6540]
*Moved from #6536*

---

I'm running:
- **Parity version**: Parity/v1.8.0-unstable-b731ccea1-20170903/x86_64-linux-gnu/rustc1.19.0
- **Operating system**:  Linux
- **And installed**: via `pacman -S parity-git`
- **parity.js** installed via `npm i @parity/parity.js`

---

What I tried:
```js
// adapted from the README.md
const Api = require('@parity/parity.js').Api;
const transport = new Api.Transport.Http('http://localhost:8545');
const api = new Api(transport);
const abi = [{"constant":true,"inputs":[],"name":"owner","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"},{"inputs":[],"payable":false,"stateMutability":"nonpayable","type":"constructor"}] // from a small contract
const bcode = '6060604 ... a0029' // large bytecode string
const contract = new api.newContract(abi);
contract.deploy({data: bcode});
```

Expected result: Contract deployed on Kovan network.

Actual result:

The promise is rejected with "request not found", but the transaction [appears to have succeeded](https://kovan.etherscan.io/tx/0x76161b35c213a8ce6d9073f6ece2be7fc5ce31ad9cf910670788811df4925a46):

```
parity_checkRequest(["0x76161b35c213a8ce6d9073f6ece2be7fc5ce31ad9cf910670788811df4925a46"]): -32042: Request not found.                     
pollMethod { e: parity_checkRequest: -32042: Request not found.                                
    at /home/travis/prg/protocol/node_modules/@parity/parity.js/library.js:1:161621            
    at <anonymous>     
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)                       
  code: -32042,        
  type: 'REQUEST_NOT_FOUND',                   
  method: 'parity_checkRequest',               
  text: 'Request not found.' }                 
(node:15338) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): e: parity_checkRequest: -32042: Request not found.
```

I am running parity as an unlocked node with the following options:
```sh
ACCOUNT_LIQPROV='0x00360d2b7D240Ec0643B6D819ba81A09e40E5bCd'

parity \
  --chain kovan \
  --author $ACCOUNT_LIQPROV \
  --unlock $ACCOUNT_LIQPROV \
  --password ~/prg/keys/kovan/account_liqprov \
  --rpcport 8545 \
  --force-ui
```

### Update:

Can confirm this also occurs on version `Parity/v1.7.0-beta-5f2cabd6e-20170727/x86_64-linux-gnu/rustc1.19.0`

**Comment by travs** [comment]
This *may* be because I am running on an unlocked node.
Looking at [this](https://github.com/paritytech/parity/blob/9196c7268abad6c0f0dc872d6c5936ace5d794d8/js/src/api/contract/contract.js#L134-L138) block of code, if `postTransaction` returns a hash, as it does in [the unlocked node case](https://github.com/paritytech/parity/wiki/JSONRPC-parity-module#returns-29) then maybe this confuses the next function in the block, which expects an id.

**Comment by travs** [comment]
With @tomusdrw : Moved [here](https://github.com/paritytech/parity.js/issues/2) ; PR there shortly
