### ISSUE TITLE
UI: Bug when opening Multisig

### ISSUE THREAD

**Issue by chevdor** [paritytech/parity#6576]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Parity version**: master
> - **Operating system**: MacOS 
> - **And installed**:  from source

Click on a multisig (no matter how many cosigners).
- The list of past TX wont
- trying to send a tx from the account fails getting ANY account as cosigner
```

Error in event handler for runtime.onMessage: Error: Syntax error, unrecognized expression: input#
    at Function.Sizzle.error (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:1580:8)
    at Sizzle.tokenize (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2232:11)
    at Sizzle.select (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2659:20)
    at Function.Sizzle [as find] (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:884:9)
    at jQuery.fn.init.find (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2922:11)
    at jQuery.fn.init (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:3032:32)
    at jQuery (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:98:10)
    at Object.cipFields.setUniqueId (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:379:19)
    at HTMLInputElement.<anonymous> (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:430:14)
    at Function.each (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:362:19)
11:16:51.155 :8180/#/wallet/0x03aF341f995F2DB8aB3fE7cf760fca828f39a006:1 Error in event handler for runtime.onMessage: Error: Syntax error, unrecognized expression: input#
    at Function.Sizzle.error (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:1580:8)
    at Sizzle.tokenize (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2232:11)
    at Sizzle.select (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2659:20)
    at Function.Sizzle [as find] (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:884:9)
    at jQuery.fn.init.find (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2922:11)
    at jQuery.fn.init (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:3032:32)
    at jQuery (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:98:10)
    at Object.cipFields.setUniqueId (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:379:19)
    at HTMLInputElement.<anonymous> (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:430:14)
    at Function.each (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:362:19)
11:16:51.657 :8180/#/wallet/0x03aF341f995F2DB8aB3fE7cf760fca828f39a006:1 Error in event handler for runtime.onMessage: Error: Syntax error, unrecognized expression: input#
    at Function.Sizzle.error (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:1580:8)
    at Sizzle.tokenize (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2232:11)
    at Sizzle.select (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2659:20)
    at Function.Sizzle [as find] (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:884:9)
    at jQuery.fn.init.find (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2922:11)
    at jQuery.fn.init (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:3032:32)
    at jQuery (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:98:10)
    at Object.cipFields.setUniqueId (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:379:19)
    at HTMLInputElement.<anonymous> (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:430:14)
    at Function.each (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:362:19)
11:16:52.157 :8180/#/wallet/0x03aF341f995F2DB8aB3fE7cf760fca828f39a006:1 Error in event handler for runtime.onMessage: Error: Syntax error, unrecognized expression: input#
    at Function.Sizzle.error (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:1580:8)
    at Sizzle.tokenize (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2232:11)
    at Sizzle.select (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2659:20)
    at Function.Sizzle [as find] (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:884:9)
    at jQuery.fn.init.find (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2922:11)
    at jQuery.fn.init (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:3032:32)
    at jQuery (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:98:10)
    at Object.cipFields.setUniqueId (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:379:19)
    at HTMLInputElement.<anonymous> (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:430:14)
    at Function.each (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:362:19)
11:16:52.657 :8180/#/wallet/0x03aF341f995F2DB8aB3fE7cf760fca828f39a006:1 Error in event handler for runtime.onMessage: Error: Syntax error, unrecognized expression: input#
    at Function.Sizzle.error (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:1580:8)
    at Sizzle.tokenize (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2232:11)
    at Sizzle.select (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2659:20)
    at Function.Sizzle [as find] (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:884:9)
    at jQuery.fn.init.find (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:2922:11)
    at jQuery.fn.init (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:3032:32)
    at jQuery (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:98:10)
    at Object.cipFields.setUniqueId (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:379:19)
    at HTMLInputElement.<anonymous> (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/mooltipass-content.js:430:14)
    at Function.each (chrome-extension://ffemldjbbfhimggdkkckolidemlllklk/vendor/jquery-3.2.1.js:362:19)
```

I tested without any extension loaded and get the same result.
The loader keeps spinning foreva!
---

**Comment by 5chdn** [comment]
The logs suggest there is some chrome extension issue. What is `chrome-extension://ffemldjbbfhimggdkkckolidemlllklk`? Is it Mooltipass?

https://chrome.google.com/webstore/detail/mooltipass-extension/ffemldjbbfhimggdkkckolidemlllklk?hl=en

**Comment by chevdor** [comment]
@5chdn Did you see my comment about testing as well without any extension and getting the same issue?

**Comment by 5chdn** [comment]
Yes, but you would need to provide logs that indicate what's going on after you remove the mooltipass extension. The errors above are coming from that extension.
