### ISSUE TITLE
Crash when running 1.8.0-beta

### ISSUE THREAD

**Issue by hydrarulz** [paritytech/parity#6798]
> I'm running:
>
> - **Parity version**: Parity/v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0
> - **Operating system**: Linux
> - **And installed**: via binaries

Actual behaviour running crashed. This is the end of the console log before crashing

```
2017-10-16 20:02:20  Imported #4372087 d09d…735c (97 txs, 6.69 Mgas, 546.23 ms, 22.13 KiB) + another 2 block(s) containing 253 tx(s)
2017-10-16 20:02:39  Imported #4372088 03df…5fc5 (5 txs, 0.11 Mgas, 3.11 ms, 2.11 KiB)
2017-10-16 20:02:42  Syncing #4372088 03df…5fc5     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #4372084    4/25 peers   6 MiB chain 84 MiB db 0 bytes queue 18 MiB sync  RPC:  1 conn,  0 req/s, 34026 µs

====================

stack backtrace:
   0:     0x55c89948ddfc - <no info>

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860

```

Expected behaviour not crashing

**Comment by misterigl** [comment]
Same bug, I'm running:

> Parity version: Parity/v1.8.0-beta-9882902-20171015/x86_64-linux-gnu/rustc1.20.0
> Operating system: Linux
> And installed: via binaries

After crashing the first time on 'IO Worker #2', it now crashes directly after starting on 'main':

``` 
2017-10-17 09:14:24  State DB configuration: fast
2017-10-17 09:14:24  Operating mode: active
2017-10-17 09:14:24  Configured for Foundation using Ethash engine
2017-10-17 09:14:24  Updated conversion rate to Ξ1 = US$328.83 (362033950 wei/gas)

====================

stack backtrace:
   0:     0x561cd7a52dfc - <no info>

Thread 'main' panicked at 'failed to update version: "Corruption: block checksum mismatch"', /checkout/src/libcore/result.rs:860
```

**Comment by 5chdn** [comment]
Your database is corrupted, please run `parity db kill` and try again.

**Comment by hydrarulz** [comment]
I've already deleted `/chains` directory and tried again and I got the same error. I'm trying with `parity 1.7.7`  now to see if I get the same error

**Comment by 5chdn** [comment]
If this keeps coming back, you might want to do a health-check on your disk.

**Comment by hydrarulz** [comment]
@5chdn already did a `fsck` too.
