### ISSUE TITLE
Thread 'IO Worker #0' panicked at 'called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity'

### ISSUE THREAD

**Issue by nicksavers** [paritytech/parity#7106]
I'm running:
- **Which Parity version?**: v1.9.0-unstable-d105bc2-20171120
- **Which operating system?**: Linux Ubuntu 16.04 LTS
- **How installed?**: from source
- **Are you fully synchronized?**: no
- **Did you try to restart the node?**: yes
- **Hardware?**: VPS provider - 2 CPU, 4GB, 80GB SSD

When running from source on the latest commit, I keep getting the following error

```bash
ethdev@parity02:~/parity$ cargo run --release --bin parity -- --no-ui
    Finished release [optimized] target(s) in 0.1 secs
     Running `target/release/parity --no-ui`
2017-11-21 04:21:36  Starting Parity/v1.9.0-unstable-d105bc2-20171120/x86_64-linux-gnu/rustc1.21.0
2017-11-21 04:21:36  Keys path /home/ethdev/.local/share/io.parity.ethereum/keys/Foundation
2017-11-21 04:21:36  DB path /home/ethdev/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2017-11-21 04:21:36  Path to dapps /home/ethdev/.local/share/io.parity.ethereum/dapps
2017-11-21 04:21:36  State DB configuration: fast
2017-11-21 04:21:36  Operating mode: active
2017-11-21 04:21:36  Configured for Foundation using Ethash engine
2017-11-21 04:21:36  Updated conversion rate to Ξ1 = US$363.15 (327819420 wei/gas)
2017-11-21 04:21:36  Removed existing file '/home/ethdev/.local/share/io.parity.ethereum/jsonrpc.ipc'.
2017-11-21 04:21:41  Public node URL: enode://9b9cba685b8433706ff7c03ce076532f212099d5df7489818dd16042b4760059398152189f92d53e60b00609867d972aa712f4989e1fb17bd77a6f87036f9100@162.220.52.17:30303
2017-11-21 04:21:46  Syncing snapshot 0/496        #0    5/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:21:51  Syncing snapshot 0/496        #0    5/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:21:56  Syncing snapshot 1/496        #0    6/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:06  Syncing snapshot 3/496        #0    7/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:11  Syncing snapshot 4/496        #0    7/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:16  Syncing snapshot 4/496        #0    8/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:26  Syncing snapshot 6/496        #0    8/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:31  Syncing snapshot 7/496        #0    9/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:41  Syncing snapshot 8/496        #0    9/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:22:46  Syncing snapshot 9/496        #0   11/25 peers   8 KiB chain 3 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
......
2017-11-21 04:34:21  Syncing snapshot 114/496        #0   49/50 peers   8 KiB chain 3 MiB db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:34:26  Syncing snapshot 115/496        #0   49/50 peers   8 KiB chain 3 MiB db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:34:31  Syncing snapshot 116/496        #0   49/50 peers   8 KiB chain 3 MiB db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:34:36  Syncing snapshot 117/496        #0   49/50 peers   8 KiB chain 3 MiB db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs
2017-11-21 04:34:41  Syncing snapshot 118/496        #0   50/50 peers   8 KiB chain 3 MiB db 0 bytes queue 19 KiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

stack backtrace:
   0:     0x55c61f65d48c - backtrace::backtrace::trace::h7d214ae0f4075a7c
   1:     0x55c61f65d4c2 - backtrace::capture::Backtrace::new::h20b025d2ae14e9dc
   2:     0x55c61ecb6c98 - panic_hook::panic_hook::hdb5978b63858b408
   3:     0x55c61f911706 - std::panicking::rust_panic_with_hook
                        at /checkout/src/libstd/panicking.rs:612
   4:     0x55c61f911524 - std::panicking::begin_panic<alloc::string::String>
                        at /checkout/src/libstd/panicking.rs:572
   5:     0x55c61f911499 - std::panicking::begin_panic_fmt
                        at /checkout/src/libstd/panicking.rs:522
   6:     0x55c61f91142a - std::panicking::rust_begin_panic
                        at /checkout/src/libstd/panicking.rs:498
   7:     0x55c61f94ac00 - core::panicking::panic_fmt
                        at /checkout/src/libcore/panicking.rs:71
   8:     0x55c61f689f72 - core::result::unwrap_failed::hc6979c457ca5c744
   9:     0x55c61f68c1b3 - ethcore_logger::setup_log::{{closure}}::hec7746b3ad8e09b6
  10:     0x55c61f6bbbc1 - <env_logger::Logger as log::Log>::log::h303c6a72f206934c
  11:     0x55c61f8c4efa - log::__log::hd081b0bbfd96a6da
  12:     0x55c61ebc2e21 - <parity::informant::Informant<T> as ethcore_io::IoHandler<ethcore::service::ClientIoMessage>>::timeout::h7478297d192509f5
  13:     0x55c61ef9eaaa - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d28235ac45ed41d
  14:     0x55c61efa4c06 - std::panicking::try::do_call::hfb492a272d3a4a75
  15:     0x55c61f9181eb - panic_abort::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_abort/lib.rs:38

Thread 'IO Worker #0' panicked at 'called `Result::unwrap()` on an `Err` value: CapacityError: insufficient capacity', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)
```

**Comment by nicksavers** [comment]
I just tried with `v1.8.3-unstable-b49c44a-20171114` and that still works. 
I'll try to narrow it down later to a specific commit.

**Comment by jacogr** [comment]
Getting the same on Kovan with version compiled from master as of this morning.

**Comment by chevdor** [comment]
Getting the same on mainnet, OSX, master (Parity/v1.9.0-unstable-a2c48deab-20171121/x86_64-macos/rustc1.21.0).

I synced back a few weeks. It seems to always occur after a little while: it chew a few blocks (few minutes) then crashes. Restarting parity allows it to go further until it crashes again.
It crashed around 10 times to sync 20 days of data.

**Comment by nicksavers** [comment]
Confirmed that this is solved.
Tested with `Parity/v1.9.0-unstable-68db425-20171124/x86_64-linux-gnu/rustc1.21.0`
