### ISSUE TITLE
Parity client does not trigger pendingTransactions event on Web socket RPC connection.

### ISSUE THREAD

**Issue by artemii235** [paritytech/parity#7152]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Docker v1.8.3 - Ropsten network
> - **Which operating system?**: Docker: v1.8.3
> - **How installed?**: Docker
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
**steps to reproduce**
1. `docker pull parity/parity:v1.8.3`
1. `docker run -it parity/parity:v1.8.3 --no-ui -p 8546:8546 --chain="ropsten" --ws-origins="all" --ws-interface="all"`
1. Wait until client syncs.
1. Attach web3 `pendingTransactions` event handler:
```
const webSocketProvider = new Web3.providers.WebsocketProvider('ws://localhost:8546');`
const web3 = new Web3(webSocketProvider);`
web3.eth.subscribe('pendingTransactions', (error, result) => {
      console.log('error received');
      console.log(error);
      console.log('result received');
      console.log(result);
});
```
***Actual output produced***
```
error received
Error: Returned error: This request is not implemented yet. Please create an issue on Github repo.
    at Object.ErrorResponse (/usr/src/app/node_modules/web3-core-helpers/src/errors.js:29:16)
    at Object.<anonymous> (/usr/src/app/node_modules/web3-core-requestmanager/src/index.js:137:36)
    at /usr/src/app/node_modules/web3-providers-ws/src/index.js:76:44
    at Array.forEach (<anonymous>)
    at W3CWebSocket.WebsocketProvider.connection.onmessage (/usr/src/app/node_modules/web3-providers-ws/src/index.js:53:36)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/usr/src/app/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/usr/src/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:115:13)
    at WebSocketConnection.emit (events.js:210:7)
    at WebSocketConnection.processFrame (/usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:547:26)
    at /usr/src/app/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
result received
null
```
***Expected output***
Pending transaction data according to web3.js subscribe API: https://web3js.readthedocs.io/en/1.0/web3-eth-subscribe.html#subscribe-pendingtransactions
This issue is also mentioned in Web3 project: https://github.com/ethereum/web3.js/issues/992

P.S. fixing this will improve UX of Dapps relying on Parity client, allowing to display pending transactions immediately just like on etherscan. Also this event works fine with Geth.

**Comment by artemii235** [comment]
I have found that this issue is duplicate of https://github.com/paritytech/parity/issues/6426, I'm closing this. Will wait for this event to be implemented in next versions.
