### ISSUE TITLE
Failure to send transactions through web3 1.0 using Websocket or IPC providers

### ISSUE THREAD

**Issue by TrekDev** [paritytech/parity#7178]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: `Parity/v1.8.3-beta-b49c44a19-20171114/x86_64-linux-gnu/rustc1.21.0`
> - **Which operating system?**: Arch Linux
> - **How installed?**: pacman
> - **Are you fully synchronized?**: yes
> - **Did you try to restart the node?**: yes

This could either be a web3 or parity issue. Apologies if this turns out to be a web3 issue. I've brought this up as an issue with web3 but haven't got a response yet: https://github.com/ethereum/web3.js/issues/1202

Web3:  `1.0.0-beta.26`
Provider: `let provider = new web3.providers.WebsocketProvider('ws://127.0.0.1:8546');`
```
# config.toml
[websockets]
#  JSON-RPC will be listening for connections on IP all.
interface = "all"
# Allow connections only using specified addresses.
hosts = ["all"]
# Only selected APIs will be exposed over this interface.
apis = ["web3", "eth", "net", "personal", "parity", "parity_accounts", "rpc", "traces", "secretstore", "parity_pubsub"]
# Allows connecting from Origin 'all'.
origins = ["all"]
```

Can send txs with HTTP provider but get this with websockets:

```
api_1      | Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
api_1      | {}
api_1      |     at Object._fireError (/app/node_modules/web3-utils/src/index.js:56:17)
api_1      |     at Subscription.checkConfirmation [as callback] (/app/node_modules/web3-core-method/src/index.js:383:26)
api_1      |     at /app/node_modules/web3-core-subscriptions/src/subscription.js:296:19
api_1      |     at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:137:20)
api_1      |     at /app/node_modules/web3-providers-ws/src/index.js:76:44
api_1      |     at Array.forEach (<anonymous>)
api_1      |     at W3CWebSocket.WebsocketProvider.connection.onmessage (/app/node_modules/web3-providers-ws/src/index.js:53:36)
api_1      |     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/node_modules/yaeti/lib/EventTarget.js:107:17)
api_1      |     at W3CWebSocket.onMessage (/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)
api_1      |     at WebSocketConnection.<anonymous> (/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)
api_1      |     at WebSocketConnection.emit (events.js:159:13)
api_1      |     at WebSocketConnection.processFrame (/app/node_modules/websocket/lib/WebSocketConnection.js:547:26)
api_1      |     at /app/node_modules/websocket/lib/WebSocketConnection.js:321:40
api_1      |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
api_1      |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

Similar error using IPC provider:
`let provider = new web.providers.IpcProvider('/app/mnt/parity/jsonrpc.ipc', net);`
```
api_1      | Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
api_1      | {}
api_1      |     at Object._fireError (/app/node_modules/web3-utils/src/index.js:56:17)
api_1      |     at Subscription.checkConfirmation [as callback] (/app/node_modules/web3-core-method/src/index.js:383:26)
api_1      |     at /app/node_modules/web3-core-subscriptions/src/subscription.js:296:19
api_1      |     at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:137:20)
api_1      |     at callback (/app/node_modules/web3-providers-ipc/src/index.js:65:40)
api_1      |     at Array.forEach (<anonymous>)
api_1      |     at Socket.<anonymous> (/app/node_modules/web3-providers-ipc/src/index.js:76:51)
api_1      |     at Socket.emit (events.js:159:13)
api_1      |     at addChunk (_stream_readable.js:265:12)
api_1      |     at readableAddChunk (_stream_readable.js:252:11)
api_1      |     at Socket.Readable.push (_stream_readable.js:209:10)
api_1      |     at Pipe.onread (net.js:598:20)
```

**Comment by tomusdrw** [comment]
Could you run Parity with `-lrpc=trace` and post the logs here? I'm interested what call is made by web3.

**Comment by TrekDev** [comment]
Sure, here it is.
```
parity_1   | 2017-12-01 13:28:59 UTC Verifier #1 INFO import  Imported #65 ab4d…807d (0 txs, 0.00 Mgas, 0.42 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:00 UTC IO Worker #1 INFO import     2/25 peers      2 MiB chain    1 MiB db  0 bytes queue   29 KiB sync  RPC:  1 conn,  7 req/s, 1161 µs
parity_1   | 2017-12-01 13:29:04 UTC Verifier #3 INFO import  Imported #66 e484…d46e (0 txs, 0.00 Mgas, 0.46 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:08 UTC Verifier #1 INFO import  Imported #67 fdfe…e7eb (0 txs, 0.00 Mgas, 0.40 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:11 UTC Verifier #0 INFO import  Imported #68 ec51…1461 (0 txs, 0.00 Mgas, 0.32 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:15 UTC Verifier #3 INFO import  Imported #69 7bec…2cb9 (0 txs, 0.00 Mgas, 0.49 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:19 UTC Verifier #2 INFO import  Imported #70 b4d5…32ae (0 txs, 0.00 Mgas, 0.32 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":34,"method":"eth_call","params":[{"data":"0x23218e5f","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000000000000000000000000000000000000000000f","id":34}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":35,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000000","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000416fd4e6c84634b42fe9556dcd8995e99031bb53","id":35}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":36,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x416fd4e6c84634b42fe9556dcd8995e99031bb53"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000005537061726b000000000000000000000000000000000000000000000000000000","id":36}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":37,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000001","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000081fad4f05e5b07510655f43c52bd5d718c05284e","id":37}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":38,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x81fad4f05e5b07510655f43c52bd5d718c05284e"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000d4669727374205574696c69747900000000000000000000000000000000000000","id":38}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":39,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000002","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000da1a8afd9158db7fab85cd3dcf961a33260c8bbb","id":39}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":40,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0xda1a8afd9158db7fab85cd3dcf961a33260c8bbb"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000014476f204566666f72746c65737320456e65726779000000000000000000000000","id":40}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":41,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000003","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000009505e8a9610c2c94f0614fe4fcd30d4f1414d0f9","id":41}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":42,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x9505e8a9610c2c94f0614fe4fcd30d4f1414d0f9"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000b5075726520506c616e6574000000000000000000000000000000000000000000","id":42}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":43,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000004","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000a8956657fb7243c5d5736f6a6a4897bf33118b14","id":43}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":44,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0xa8956657fb7243c5d5736f6a6a4897bf33118b14"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a526f62696e20486f6f6400000000000000000000000000000000000000000000","id":44}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":45,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000005","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000398b3f97bf088938326a07bc9f79a4dbd5ea8f96","id":45}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":46,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x398b3f97bf088938326a07bc9f79a4dbd5ea8f96"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000094f757220506f7765720000000000000000000000000000000000000000000000","id":46}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":47,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000006","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000007f1ac743c665b616356cb6a0b8f1c1efae449120","id":47}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":48,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x7f1ac743c665b616356cb6a0b8f1c1efae449120"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000004452e4f4e00000000000000000000000000000000000000000000000000000000","id":48}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":49,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000007","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000bfb50c0b852745afd89ecadcb91d72d8c807341b","id":49}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":50,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0xbfb50c0b852745afd89ecadcb91d72d8c807341b"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000064e706f7765720000000000000000000000000000000000000000000000000000","id":50}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":51,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000008","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000f7b3ebdcd9cf879f46ca39f0324565333fb86544","id":51}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":52,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0xf7b3ebdcd9cf879f46ca39f0324565333fb86544"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c477265656e20456e657267790000000000000000000000000000000000000000","id":52}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":53,"method":"eth_call","params":[{"data":"0x65e406cd0000000000000000000000000000000000000000000000000000000000000009","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000004669b035f759638f1c25f07a62232b62bde1ff73","id":53}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":54,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x4669b035f759638f1c25f07a62232b62bde1ff73"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c546f6e696b20456e657267790000000000000000000000000000000000000000","id":54}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":55,"method":"eth_call","params":[{"data":"0x65e406cd000000000000000000000000000000000000000000000000000000000000000a","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000005274dec2752c1f5ed15b53933001d821389412b9","id":55}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":56,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x5274dec2752c1f5ed15b53933001d821389412b9"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000e45636f6e6f6d7920656e65726779000000000000000000000000000000000000","id":56}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":57,"method":"eth_call","params":[{"data":"0x65e406cd000000000000000000000000000000000000000000000000000000000000000b","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000016f111b773397bd27c3d2289943ff2dd84a61c1f","id":57}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":58,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x16f111b773397bd27c3d2289943ff2dd84a61c1f"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a4f766f20456e6572677900000000000000000000000000000000000000000000","id":58}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":59,"method":"eth_call","params":[{"data":"0x65e406cd000000000000000000000000000000000000000000000000000000000000000c","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000350154a8e949941f079989636833fee867c35f2d","id":59}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":60,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x350154a8e949941f079989636833fee867c35f2d"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000f546f67657468657220456e657267790000000000000000000000000000000000","id":60}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":61,"method":"eth_call","params":[{"data":"0x65e406cd000000000000000000000000000000000000000000000000000000000000000d","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:23 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x000000000000000000000000c2e766f32b6b467c444123751a09ba6430f1e616","id":61}.
parity_1   | 2017-12-01 13:29:23 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":62,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0xc2e766f32b6b467c444123751a09ba6430f1e616"},"latest"]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000009534f20456e657267790000000000000000000000000000000000000000000000","id":62}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":63,"method":"eth_call","params":[{"data":"0x65e406cd000000000000000000000000000000000000000000000000000000000000000e","to":"0x6c8bef723a7df71309dca1e401bcfda26fcc97d2"},"latest"]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0000000000000000000000002239ffcd60a8352bfe4ef4fcabbdff01314cddfd","id":63}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":64,"method":"eth_call","params":[{"data":"0x17d7de7c","to":"0x2239ffcd60a8352bfe4ef4fcabbdff01314cddfd"},"latest"]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000006476e455247590000000000000000000000000000000000000000000000000000","id":64}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":65,"method":"personal_unlockAccount","params":["0x0c56cbc923106cba453019aadf2c1d145dde3e52","NdFIY89vUlwuARsUFzTOG8oyGA+/4gTjK6K8LcWsaNohD8PTZqQM/on2PhZzvX6C6xAPxUvI0CiUmGMlc5bSFQ==","0x000000000000000000000000000001f4"]}.
parity_1   | 2017-12-01 13:29:24 UTC Verifier #0 INFO import  Imported #71 0e2d…1f7e (0 txs, 0.00 Mgas, 0.45 ms, 0.56 KiB)
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  [Some(Num(65))] Took 15ms
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":true,"id":65}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":66,"method":"eth_gasPrice","params":[]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x0","id":66}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":67,"method":"eth_sendTransaction","params":[{"from":"0x0c56cbc923106cba453019aadf2c1d145dde3e52","data":"0x6060604052341561000f57600080fd5b6040516103a83803806103a8833981016040528080518201919050508060009080519060200190610041929190610048565b50506100ed565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f1061008957805160ff19168380011785556100b7565b828001600101855582156100b7579182015b828111156100b657825182559160200191906001019061009b565b5b5090506100c491906100c8565b5090565b6100ea91905b808211156100e65760008160009055506001016100ce565b5090565b90565b6102ac806100fc6000396000f300606060405260043610610057576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff16806317d7de7c1461005c57806349b674cc146100ea578063e58e57761461011c575b600080fd5b341561006757600080fd5b61006f61015b565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156100af578082015181840152602081019050610094565b50505050905090810190601f1680156100dc5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34156100f557600080fd5b61011a6004808035600019169060200190919080351515906020019091905050610203565b005b341561012757600080fd5b61014160048080356000191690602001909190505061023a565b604051808215151515815260200191505060405180910390f35b61016361026c565b60008054600181600116156101000203166002900480601f0160208091040260200160405190810160405280929190818152602001828054600181600116156101000203166002900480156101f95780601f106101ce576101008083540402835291602001916101f9565b820191906000526020600020905b8154815290600101906020018083116101dc57829003601f168201915b5050505050905090565b8060016000846000191660001916815260200190815260200160002060006101000a81548160ff0219169083151502179055505050565b600060016000836000191660001916815260200190815260200160002060009054906101000a900460ff169050919050565b6020604051908101604052806000815250905600a165627a7a723058203da3dcb3c6cb30b2b7dfd8067ca4528d71c5de6579f1cf1eae19c403baec48920029000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000096d795f6e65775f74780000000000000000000000000000000000000000000000","gasPrice":"0x0"}]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  [Some(Num(67))] Took 14ms
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":"0x245428cd5f71d4058ab6855c195a8af67c9dc7eccbb739344fbe31cb3da35878","id":67}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":68,"method":"eth_getTransactionReceipt","params":["0x245428cd5f71d4058ab6855c195a8af67c9dc7eccbb739344fbe31cb3da35878"]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","result":null,"id":68}.
parity_1   | 2017-12-01 13:29:24 UTC  TRACE rpc  Request: {"jsonrpc":"2.0","id":69,"method":"eth_subscribe","params":["newHeads"]}.
parity_1   | 2017-12-01 13:29:24 UTC  DEBUG rpc  Response: {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":69}.
api_1      | Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.
api_1      | {}
api_1      |     at Object._fireError (/app/node_modules/web3-utils/src/index.js:56:17)
api_1      |     at Subscription.checkConfirmation [as callback] (/app/node_modules/web3-core-method/src/index.js:383:26)
api_1      |     at /app/node_modules/web3-core-subscriptions/src/subscription.js:296:19
api_1      |     at Object.<anonymous> (/app/node_modules/web3-core-requestmanager/src/index.js:137:20)
api_1      |     at /app/node_modules/web3-providers-ws/src/index.js:76:44
api_1      |     at Array.forEach (<anonymous>)
api_1      |     at W3CWebSocket.WebsocketProvider.connection.onmessage (/app/node_modules/web3-providers-ws/src/index.js:53:36)
api_1      |     at W3CWebSocket._dispatchEvent [as dispatchEvent] (/app/node_modules/yaeti/lib/EventTarget.js:107:17)
api_1      |     at W3CWebSocket.onMessage (/app/node_modules/websocket/lib/W3CWebSocket.js:234:14)
api_1      |     at WebSocketConnection.<anonymous> (/app/node_modules/websocket/lib/W3CWebSocket.js:205:19)
api_1      |     at WebSocketConnection.emit (events.js:159:13)
api_1      |     at WebSocketConnection.processFrame (/app/node_modules/websocket/lib/WebSocketConnection.js:547:26)
api_1      |     at /app/node_modules/websocket/lib/WebSocketConnection.js:321:40
api_1      |     at _combinedTickCallback (internal/process/next_tick.js:131:7)
api_1      |     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by TrekDev** [comment]
That was with the websocket provider. The HTTP provider completes successfully.

**Comment by tomusdrw** [comment]
pubsub is supported on 1.8.3, please make sure that you don't run with `--public-node or --ws-apis` that don't expose `eth_pubsub` namespace.

**Comment by TrekDev** [comment]
Ah, sorry, is parity_pubsub different to eth_pubsub?

**Comment by tomusdrw** [comment]
yes, `parity_pubsub` is parity-specific generic publish/subscribe interface `parity_subscribe('eth_accounts', [])` for instance, `eth_pubsub` should be exposed for subscriptions to work.

**Comment by TrekDev** [comment]
Thanks very much. However, just trying to expose that I get
```
Loading config file from config.toml
Unknown api: eth_pubsub
```

**Comment by tomusdrw** [comment]
oh, sorry the API is actually named just `pubsub` not `eth_pubsub`

**Comment by TrekDev** [comment]
Phew, that's all working. Once again: thanks very much.

So I guess this is another parity config generator thing, since "pubsub" was missing from the WebSocket and IPC api list options...

**Comment by tomusdrw** [comment]
Thanks for a heads up, addressed here: https://github.com/paritytech/parity-config-generator/pull/28
