### ISSUE TITLE
Unexpected rlp error: RlpExpectedToBeData

### ISSUE THREAD

**Issue by LLBlumire** [paritytech/parity#7188]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.0-unstable-dde6bae-20171202/x86_64-windows-msvc/rustc1.22.1
> - **Which operating system?**: Windows
> - **How installed?**: from source
> - **Are you fully synchronized?**:  yes
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

```
C:\Users\Lucille\Documents\Code\Rust\parity>cargo run --release -- --no-warp
    Finished release [optimized] target(s) in 0.2 secs
     Running `target\release\parity.exe --no-warp`
2017-12-03 23:47:43 UTC Starting Parity/v1.9.0-unstable-dde6bae-20171202/x86_64-windows-msvc/rustc1.22.1
2017-12-03 23:47:43 UTC Keys path C:\Users\Lucille\AppData\Roaming\Parity\Ethereum\keys\Foundation
2017-12-03 23:47:43 UTC DB path C:\Users\Lucille\AppData\Local\Parity\Ethereum\chains\ethereum\db\906a34e69aec8c0d
2017-12-03 23:47:43 UTC Path to dapps C:\Users\Lucille\AppData\Roaming\Parity\Ethereum\dapps
2017-12-03 23:47:43 UTC State DB configuration: fast
2017-12-03 23:47:43 UTC Operating mode: dark
2017-12-03 23:47:43 UTC Configured for Foundation using Ethash engine
2017-12-03 23:47:44 UTC Updated conversion rate to Ξ1 = US$459.36 (259159760 wei/gas)

====================

stack backtrace:
   0:     0x7ff6aeda0967 - <error_chain::State as core::fmt::Debug>::fmt::h0552b330708c7f10
   1:     0x7ff6aeda0eee - backtrace::capture::Backtrace::new::hc091ddf47f145ac5
   2:     0x7ff6ae4657b4 - panic_hook::set::h91fcab5db65150d5
   3:     0x7ff6aedcae44 - std::panicking::rust_panic_with_hook
                        at C:\projects\rust\src\libstd\panicking.rs:578
   4:     0x7ff6aedcacb9 - std::panicking::begin_panic<alloc::string::String>
                        at C:\projects\rust\src\libstd\panicking.rs:538
   5:     0x7ff6aedcab92 - std::panicking::begin_panic_fmt
                        at C:\projects\rust\src\libstd\panicking.rs:522
   6:     0x7ff6aedcab00 - std::panicking::rust_begin_panic
                        at C:\projects\rust\src\libstd\panicking.rs:498
   7:     0x7ff6aedd402f - core::panicking::panic_fmt
                        at C:\projects\rust\src\libcore\panicking.rs:71
   8:     0x7ff6ae693257 - <hyper::version::HttpVersion as core::fmt::Debug>::fmt::h8df7a2e4c4d21910
   9:     0x7ff6ae791382 - <ethcore::client::client::Client as core::ops::drop::Drop>::drop::h34611e0e96537f0c
  10:     0x7ff6ae8d55ff - ethcore::blockchain::blockchain::BlockChain::epoch_transition::h4cd85ff072a12665
  11:     0x7ff6ae75b7ab - ethcore::client::client::Client::new::hbb3191df4748e209
  12:     0x7ff6ae806705 - ethcore::service::ClientService::start::hb3e15ded3cf04af0
  13:     0x7ff6ae209d89 - <parity_tokio_ipc::IpcStream as tokio_io::AsyncRead>::prepare_uninitialized_buffer::had351eb0f2ccb402
  14:     0x7ff6ae224d97 - <parity_tokio_ipc::IpcStream as tokio_io::AsyncRead>::prepare_uninitialized_buffer::had351eb0f2ccb402
  15:     0x7ff6ae22a8dd - <parity_tokio_ipc::IpcStream as tokio_io::AsyncRead>::prepare_uninitialized_buffer::had351eb0f2ccb402
  16:     0x7ff6ae22d026 - <parity_tokio_ipc::IpcStream as tokio_io::AsyncRead>::prepare_uninitialized_buffer::had351eb0f2ccb402
  17:     0x7ff6aedcc152 - panic_abort::__rust_maybe_catch_panic
                        at C:\projects\rust\src\libpanic_abort\lib.rs:40
  18:     0x7ff6aedcb642 - std::rt::lang_start
                        at C:\projects\rust\src\libstd\rt.rs:52
  19:     0x7ff6aef8e849 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  20:     0x7ffe0a281fe4 - BaseThreadInitThunk

Thread 'main' panicked at 'Unexpected rlp error: RlpExpectedToBeData', src\libcore\result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

**Comment by debris** [comment]
This panic is cause by corrupted database on disk. Most likely epoch was not written to a disk properly due to lack of space. https://github.com/paritytech/parity/pull/7348 should fix the issue

**Comment by 5chdn** [comment]
#7493 indicates #7348 does not fix the issue.

**Comment by lght** [comment]
I started working on a similar problem from #7493 (this issue's dup), and have a PR in #7548 for what I think might be the issue.

**Comment by rphmeier** [comment]
I don't think #7548 is related since the error here is unrelated to displaying RLP structures in string form.

**Comment by debris** [comment]
closing in favour of #8033
