### ISSUE TITLE
Parity stops; Issue: all back-references to answered requests have been filled

### ISSUE THREAD

**Issue by Shachindra** [paritytech/parity#7416]
I'm running:

> - **Which Parity version?**: v1.8.5-beta-54bae9a-20171228/x86_64-linux-gnu/rustc1.22.1
> - **Which operating system?**: VM- 4.11.0-1016-azure #16-Ubuntu
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Did you try to restart the node?**: yes (After restart no issues so far as it's still syncing)

Error: While syncing with the kovan testnet, parity abruptly gets stopped.

2018-01-01 06:39:03 UTC Syncing #4973397 5101…5fb5     0 hdr/s      0+    0 Qed  #4973397   24/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  3 req/s,  53 µs
2018-01-01 06:39:08 UTC Syncing #4973397 5101…5fb5     0 hdr/s      0+    0 Qed  #4973397   24/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  1 req/s,  53 µs
2018-01-01 06:39:13 UTC Syncing #4973397 5101…5fb5     0 hdr/s      0+    0 Qed  #4973397   23/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  3 req/s,  53 µs
2018-01-01 06:39:18 UTC Syncing #4973397 5101…5fb5     0 hdr/s      0+    0 Qed  #4973397   23/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  2 req/s,  53 µs
2018-01-01 06:39:23 UTC Syncing #4973397 5101…5fb5     0 hdr/s      0+    0 Qed  #4973397   22/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,  53 µs

====================

stack backtrace:
   0:       0x267f7a3d9c - <no info>

Thread '<unnamed>' panicked at 'all back-references to answered requests have been filled; qed: NoSuchOutput', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

Run Command: 
parity --chain kovan --light --jsonrpc-apis web3,eth,net,parity,traces,rpc,personal --jsonrpc-port 8545 --jsonrpc-interface 0.0.0.0 --jsonrpc-cors all --jsonrpc-hosts all --force-ui --ui-no-validation

**Comment by Shachindra** [comment]
Happened again even after full sync was completed:
2018-01-01 09:30:32 UTC Syncing #5194214 9123…a74c     0 hdr/s      0+    0 Qed  #5194214   25/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,  96 µs
2018-01-01 09:31:02 UTC   25/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,  97 µs
2018-01-01 09:31:32 UTC   25/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,  0 req/s,  97 µs

====================

stack backtrace:
   0:       0xcf25413d9c - <no info>

Thread '<unnamed>' panicked at 'all back-references to answered requests have been filled; qed: NoSuchOutput', /checkout/src/libcore/result.rs:906

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted (core dumped)

**Comment by debris** [comment]
@rphmeier any tips?

https://github.com/paritytech/parity/blob/594716dc1ec822feb0230c4d57e99c4810e4b813/ethcore/light/src/on_demand/mod.rs#L161-L166

**Comment by rphmeier** [comment]
Two possibilities:
  - A bug in the request batch builder or request types that leads to an invalid request chain passing the checks
  - A bug in the request batch or request types that leads to back-references not being filled correctly.
