### ISSUE TITLE
Thread 'IO Worker #2' panicked at 'index 12 out of range for slice of length 8', src/libcore/slice/mod.rs:746

### ISSUE THREAD

**Issue by Harvey-Specter** [paritytech/parity#7536]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.6
> - **Which operating system?**: MacOS 
> - **How installed?**: via installer homebrew
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: YES

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I started sync blocks from genesis ,  it does not work.

I retry many times ,the same problem

$parity --warp --db-path /Volumes/lulu256/parity_db
Option '--warp' does nothing. It's on by default.
2018-01-11 21:57:46  Starting Parity/v1.8.6-beta-2d051e4-20180109/x86_64-macos/rustc1.22.1
2018-01-11 21:57:46  Keys path /Users/lihong/Library/Application Support/io.parity.ethereum/keys/Foundation
2018-01-11 21:57:46  DB path /Volumes/lulu256/parity_db/ethereum/db/906a34e69aec8c0d
2018-01-11 21:57:46  Path to dapps /Users/lihong/Library/Application Support/io.parity.ethereum/dapps
2018-01-11 21:57:46  State DB configuration: fast
2018-01-11 21:57:46  Operating mode: active
2018-01-11 21:57:46  Configured for Foundation using Ethash engine
2018-01-11 21:57:47  Removed existing file '/Users/lihong/Library/Application Support/io.parity.ethereum/jsonrpc.ipc'.
2018-01-11 21:57:49  Updated conversion rate to Ξ1 = US$1193.08 (99781750 wei/gas)
2018-01-11 21:57:52  Public node URL: enode://1902f4fdcc2e79082286e43c13c701233dbde14a8b7085bb09112e139dfdbf55c15fa6677bff7516d5c8779ef6af5c68d190e4e9672230bc48459b8cb80e40e4@192.168.0.103:30303
2018-01-11 21:57:57  Syncing snapshot 0/807    #11504    2/25 peers   74 KiB chain 14 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  7 req/s, 132 µs
2018-01-11 21:58:02  Syncing snapshot 2/807    #11504    2/25 peers   74 KiB chain 14 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s, 132 µs
2018-01-11 21:58:07  Syncing snapshot 3/807    #11504    2/25 peers   74 KiB chain 14 MiB db 0 bytes queue 10 KiB sync  RPC:  1 conn,  0 req/s, 132 µs

====================

stack backtrace:

Thread 'IO Worker #2' panicked at 'index 12 out of range for slice of length 8', src/libcore/slice/mod.rs:746

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6

**Comment by folsen** [comment]
Closing as unreproducible, probably a disk issue.
