### ISSUE TITLE
Parity node shutdown when try to call parity's trace filter using web3j

### ISSUE THREAD

**Issue by kunalransing** [paritytech/parity#8177]
**Parity version** ->  v1.9.4-beta-6f21a32-20180228
 **operating system** -> Ubuntu 16 on AWS
 **How installed?** ->  $ bash <(curl https://get.parity.io -kL)
 **Are you fully synchronized?** ->  yes
 **Which network are you connected to?** -> kovan 
 **Did you try to restart the node?**  -> Yes.

```
$>parity --testnet --rpcapi "eth,net,web3,personal,parity,traces" --jsonrpc-cors all --jsonrpc-hosts all --jsonrpc-interface all
2018-03-21 13:59:10 UTC Starting Parity/v1.9.4-beta-6f21a32-20180228/x86_64-linux-gnu/rustc1.24.0
2018-03-21 13:59:10 UTC Keys path /root/.local/share/io.parity.ethereum/keys/Kovan
2018-03-21 13:59:10 UTC DB path /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98
2018-03-21 13:59:10 UTC Path to dapps /root/.local/share/io.parity.ethereum/dapps
2018-03-21 13:59:10 UTC State DB configuration: **fast +Trace**
2018-03-21 13:59:10 UTC Operating mode: active
2018-03-21 13:59:10 UTC Warning: Warp Sync is disabled because tracing is turned on.
2018-03-21 13:59:10 UTC Configured for Kovan using AuthorityRound engine
2018-03-21 13:59:11 UTC Removed existing file '/root/.local/share/io.parity.ethereum/jsonrpc.ipc'.
2018-03-21 13:59:13 UTC Imported #6488789 9f64…b80b (0 txs, 0.00 Mgas, 0.48 ms, 0.57 KiB)
2018-03-21 13:59:16 UTC Imported #6488790 a3e0…73b2 (0 txs, 0.00 Mgas, 0.44 ms, 0.57 KiB)
2018-03-21 13:59:16 UTC Public node URL: enode://2e4469029edb4297d633bf960fc98048ddd6a5386dcc90ba77960d85459a32dcd518bb2677f601701e2f794787a37a692c6afd9cf2b87fa94f054ebdc9bdffc1@172.31.24.138:30303
2018-03-21 13:59:20 UTC Imported #6488791 82fe…9d69 (0 txs, 0.00 Mgas, 0.45 ms, 0.57 KiB)
2018-03-21 13:59:24 UTC Imported #6488792 8616…43fd (0 txs, 0.00 Mgas, 0.52 ms, 0.57 KiB)
2018-03-21 13:59:28 UTC Imported #6488793 546f…1390 (2 txs, 0.11 Mgas, 1.16 ms, 1.29 KiB)
2018-03-21 13:59:32 UTC Imported #6488794 cbf8…f78f (1 txs, 0.05 Mgas, 0.68 ms, 0.70 KiB)
2018-03-21 13:59:36 UTC Imported #6488795 01c3…2e37 (0 txs, 0.00 Mgas, 0.52 ms, 0.57 KiB)
2018-03-21 13:59:40 UTC Imported #6488796 58d1…6618 (1 txs, 0.03 Mgas, 0.64 ms, 0.70 KiB)
2018-03-21 13:59:41 UTC    9/25 peers   96 KiB chain 90 MiB db 0 bytes queue 41 KiB sync  RPC:  0 conn,  0 req/s,  51 µs
2018-03-21 13:59:44 UTC Imported #6488797 9630…57ab (0 txs, 0.00 Mgas, 0.47 ms, 0.57 KiB)
2018-03-21 13:59:48 UTC Imported #6488798 4366…888e (1 txs, 0.27 Mgas, 1.61 ms, 1.93 KiB)
2018-03-21 13:59:52 UTC Imported #6488799 12de…b839 (1 txs, 0.27 Mgas, 1.58 ms, 1.93 KiB)
2018-03-21 13:59:56 UTC Imported #6488800 a351…dac3 (5 txs, 0.64 Mgas, 24.88 ms, 2.51 KiB)

====================

stack backtrace:
   0:     0x5652922d28dc - <no info>

Thread '<unnamed>' panicked at 'hash exists; qed', /checkout/src/libcore/option.rs:891
```

**Steps to reproduce :** 
1. This occurs when I try to call web3j's  parity trace filter.
```
		    ParityTracesResponse receivedByAddressResponse = parity.traceFilter(new TraceFilter(
		            new DefaultBlockParameterNumber(traceLastBlock.add(BigInteger.valueOf(1))),
		            DefaultBlockParameterName.LATEST,
		            null,
		            addresses
		        )).send();
```
```
Above code throws exception & also shutdown parity node
2018-03-21 14:10:43,028 SEVERE [com.enovate.eth.ETHConfig] (EJB default - 7) ETHConfig_updateReceiveCoinFromContract:Failed filter receive coin.: java.io.IOException: unexpected end of stream on Connection{{MY-AWS-IP}:8545, proxy=DIRECT hostAddress=/{MY-AWS-IP}:8545 cipherSuite=none protocol=http/1.1}
        at deployment.EP-ETH-Web.war//okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:205)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at deployment.EP-ETH-Web.war//okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at deployment.EP-ETH-Web.war//okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at deployment.EP-ETH-Web.war//okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at deployment.EP-ETH-Web.war//okhttp3.RealCall.execute(RealCall.java:69)
        at deployment.EP-ETH-Web.war//org.web3j.protocol.http.HttpService.performIO(HttpService.java:104)
        at deployment.EP-ETH-Web.war//org.web3j.protocol.Service.send(Service.java:31)
        at deployment.EP-ETH-Web.war//org.web3j.protocol.core.Request.send(Request.java:71)
        at deployment.EP-ETH-Web.war//com.enovate.eth.ETHConfig.updateReceiveCoinFromContract(ETHConfig.java:323)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        .........................................
Caused by: java.io.EOFException: \n not found: limit=0 content=…
        at deployment.EP-ETH-Web.war//okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at deployment.EP-ETH-Web.war//okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
        at deployment.EP-ETH-Web.war//okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
```

**Comment by Tbaut** [comment]
Could you reproduce this on a newer release?
