### ISSUE TITLE
Synchronization error 

### ISSUE THREAD

**Issue by moadif** [paritytech/parity#8196]
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.8.3
> - **Which operating system?**: Windows
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

This is what I get when trying to sync it for hours, I tried reinstalling multiple times and resetting database countless of times.

```
2018-03-22 18:28:06  Syncing #4369561 3cb7…b692    15 blk/s 1297 tx/s  72 Mgas/s      0+  681 Qed  #4370242   21/25 peers    256 MiB chain  267 MiB db   64 MiB queue   16 MiB sync  RPC:  0 conn,  0 req/s,   0 µs
2018-03-22 18:28:16  Syncing #4369707 ff97…a245    14 blk/s 1383 tx/s  81 Mgas/s      0+  533 Qed  #4370242   21/25 peers    257 MiB chain  267 MiB db   51 MiB queue   16 MiB sync  RPC:  0 conn,  0 req/s,   0 µs

====================

====================

stack backtrace:
   0:     0x7ff637e42054 - hid_error
   1:     0x7ff637e4255b - hid_error
   2:     0x7ff637661134 - <no info>
   3:     0x7ff637fbb564 - hid_error
   4:     0x7ff637fbb3d9 - hid_error
   5:     0x7ff637fbb2b2 - hid_error
   6:     0x7ff637fbb220 - hid_error
   7:     0x7ff637fc4b0f - hid_error
   8:     0x7ff6377f014c - <no info>
   9:     0x7ff6378c1822 - <no info>
  10:     0x7ff6377988fb - <no info>
  11:     0x7ff63779ec6a - <no info>
  12:     0x7ff637fbcb12 - hid_error
  13:     0x7ff6377f20c6 - <no info>
  14:     0x7ff637fb964c - hid_error
  15:     0x7ffe82708364 - BaseThreadInitThunk

Thread 'IO Worker #1' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', src\libcore\result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new


stack backtrace:
   0:     0x7ff637e42054 - hid_error
   1:     0x7ff637e4255b - hid_error
   2:     0x7ff637661134 - <no info>
   3:     0x7ff637fbb564 - hid_error
   4:     0x7ff637fbb3d9 - hid_error
   5:     0x7ff637fbb2b2 - hid_error
   6:     0x7ff637fbb220 - hid_error
   7:     0x7ff637fc4b0f - hid_error
   8:     0x7ff6377f014c - <no info>
   9:     0x7ff6378c1822 - <no info>
  10:     0x7ff6377988fb - <no info>
  11:     0x7ff63779ec6a - <no info>
  12:     0x7ff637fbcb12 - hid_error
  13:     0x7ff6377f20c6 - <no info>
  14:     0x7ff637fb964c - hid_error
  15:     0x7ffe82708364 - BaseThreadInitThunk

Thread 'IO Worker #0' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', src\libcore\result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new


====================

stack backtrace:
   0:     0x7ff637e42054 - hid_error
   1:     0x7ff637e4255b - hid_error
   2:     0x7ff637661134 - <no info>
   3:     0x7ff637fbb564 - hid_error
   4:     0x7ff637fbb3d9 - hid_error
   5:     0x7ff637fbb2b2 - hid_error
   6:     0x7ff637fbb220 - hid_error
   7:     0x7ff637fc4b0f - hid_error
   8:     0x7ff6377f014c - <no info>
   9:     0x7ff6378c1822 - <no info>
  10:     0x7ff6377988fb - <no info>
  11:     0x7ff63779ec6a - <no info>
  12:     0x7ff637fbcb12 - hid_error
  13:     0x7ff6377f20c6 - <no info>
  14:     0x7ff637fb964c - hid_error
  15:     0x7ffe82708364 - BaseThreadInitThunk

Thread 'IO Worker #3' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', src\libcore\result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new


====================

stack backtrace:
   0:     0x7ff637e42054 - hid_error
   1:     0x7ff637e4255b - hid_error
   2:     0x7ff637661134 - <no info>
   3:     0x7ff637fbb564 - hid_error
   4:     0x7ff637fbb3d9 - hid_error
   5:     0x7ff637fbb2b2 - hid_error
   6:     0x7ff637fbb220 - hid_error
   7:     0x7ff637fc4b0f - hid_error
   8:     0x7ff6377f014c - <no info>
   9:     0x7ff6378c1822 - <no info>
  10:     0x7ff6377988fb - <no info>
  11:     0x7ff63779ec6a - <no info>
  12:     0x7ff637fbcb12 - hid_error
  13:     0x7ff6377f20c6 - <no info>
  14:     0x7ff637fb964c - hid_error
  15:     0x7ffe82708364 - BaseThreadInitThunk

Thread 'IO Worker #2' panicked at 'DB flush failed.: "Corruption: block checksum mismatch"', src\libcore\result.rs:860

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new`


```

**Comment by 5chdn** [comment]
Please upgrade, this has been addressed!
