### ISSUE TITLE
when require() fails, eth_call behavior different between parity and truffle develop

### ISSUE THREAD

**Issue by umegaya** [paritytech/parity#8442]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.9.6-stable-df92977-20180416/x86_64-macos/rustc1.25.0
> - **Which operating system?**: MacOS
> - **How installed?**: homebrew
> - **Are you fully synchronized?**: yes (my own PoA chain)
> - **Which network are you connected to?**: private PoA chain
> - **Did you try to restart the node?**: yes

partiy and truffle develop chain behavior different, when running solidity code by eth_call raises error by failure of __require()__.

I expect jsonrpc to return error code when require fails, and if contract deployed into truffle develop, it behaves as I expect. but at same situation, parity returned strange success response like ```{"jsonrpc":"2.0","result":"0x","id":114}```. 

its expected behavior for parity? if so, can I match parity behavior to truffle develop one with some configuration? 

- contract code 
  ```
  contract Test {
    function testCall(uint slot_index) public returns (uint) {
        require(slot_index < 1);
        return slot_index + 100;
    }
  }
  ```

- attempt to call Test.testCall(1) for the contract deployed into truffle develop (expected)
  ```
  # returns error
  $ curl --data '{"jsonrpc":"2.0","id":114,"method":"eth_call","params":[{"from":"0x627306090abab3a6e1400e9345bc60c78a8bef57","gas":"0x4630c0","gasPrice":"0x174876e800","to":"0x98fd7bd970f4fab598d810d4194167cadf3d3941","data":"0xd0a9c0430000000000000000000000000000000000000000000000000000000000000001"},"latest"]}' -H "Content-Type: application/json" -X POST localhost:9545
  {"id":114,"jsonrpc":"2.0","error":{"message":"VM Exception while processing transaction: revert","code":-32000,"data":{"stack":"c: VM Exception while processing transaction: revert\n    at Function.c.fromResults (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:249491)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:472538\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:1997573\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:89329\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:74827\n    at o (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:77901)\n    at f (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:77858)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:77651\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:89263\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:1997507\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:2788297\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:74827\n    at o (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:77901)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:77974\n    at Ut (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:87338)\n    at Object.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:78056)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:2788230\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:77651\n    at c (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:92705)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:2788188\n    at c (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:92665)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:2788163\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:146368\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:257472\n    at f (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:262473)\n    at /usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:257408\n    at Immediate._onImmediate (/usr/local/lib/node_modules/truffle/build/webpack:/~/ganache-cli/build/lib.node.js?44e2:1:273039)\n    at runCallback (timers.js:757:18)\n    at tryOnImmediate (timers.js:718:5)\n    at processImmediate [as _immediateCallback] (timers.js:698:5)","name":"c"}}}
  ```

- attempt to call Test.testCall(1) for the contract deployed into parity (unexpected)
  ```
  # returns success with strange result (0x only)
  $ curl --data '{"jsonrpc":"2.0","id":114,"method":"eth_call","params":[{"from":"0x7846ea1ac51195783f98b732ac8db903c4ced3ae","gas":"0x4630c0","gasPrice":"0x174876e800","to":"0xf7050f561b0b9d4301a8d78b44de06c8861b8fc9","data":"0xd0a9c0430000000000000000000000000000000000000000000000000000000000000001"},"latest"]}' -H "Content-Type: application/json" -X POST localhost:8540
  {"jsonrpc":"2.0","result":"0x","id":114}
  ```

regards,

**Comment by sorpaas** [comment]
It looks like we store all errors in `Executed` struct, and `eth_call` ignores any `Executed::exception`. The spec does not say anything about this. Is this the expected behavior? Or should we change `eth_call` to return errors in case `Executed::exception.is_some()`?

**Comment by tomusdrw** [comment]
@sorpaas Indeed it's not specified, imho it makes sense to return errors there.
