### ISSUE TITLE
Syncing crashed with message: Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', libcore/option.rs:917

### ISSUE THREAD

**Issue by schmidsi** [paritytech/parity#8445]
> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.1-beta-45c29a2-20180413/x86_64-macos/rustc1.25.0
> - **Which operating system?**: MacOS 10.13.4 (17E199)
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no (error happened while syncing over night)
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: no

I was running the node overnight to sync. In the morning I came back and saw this error:

```
$ parity 
Loading config file from /Users/schmidsi/Library/Application Support/io.parity.ethereum/config.toml
2018-04-19 19:19:09  Starting Parity/v1.10.1-beta-45c29a2-20180413/x86_64-macos/rustc1.25.0
2018-04-19 19:19:09  Keys path /Users/schmidsi/Library/Application Support/io.parity.ethereum/keys/Foundation
2018-04-19 19:19:09  DB path /Volumes/EXTERNAL/Parity/ethereum/db/906a34e69aec8c0d
2018-04-19 19:19:09  Path to dapps /Users/schmidsi/Library/Application Support/io.parity.ethereum/dapps
2018-04-19 19:19:09  State DB configuration: fast
2018-04-19 19:19:09  Operating mode: active
2018-04-19 19:19:09  Configured for Foundation using Ethash engine
2018-04-19 19:19:10  Updated conversion rate to Ξ1 = US$557.57 (8540460 wei/gas)
2018-04-19 19:19:11  Public node URL: enode://fd9ca10dc6edd9bd185cc99c737c29f1d4d882bcd8c6369b06cfc1adea85d2e3b049f8f3d2360a881fb11047f2d6f775b6c6eedd401f9ca8fd774fe6b4304d98@192.168.0.11:30303
2018-04-19 19:19:14  Error sending a subscription update: Error(ConnectionClosed, State { next_error: None, backtrace: None })
2018-04-19 19:19:15  Cannot send notification: SendError("...")
2018-04-19 19:19:15  Cannot send notification: SendError("...")
2018-04-19 19:19:21  Syncing #5224706 c393…5212     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5224706    1/25 peers   3 MiB chain 71 MiB db 0 bytes queue 174 KiB sync  RPC:  1 conn, 33 req/s,  54 µs
2018-04-19 19:19:31  Syncing #5224708 9efc…61cd     0 blk/s   25 tx/s   1 Mgas/s      0+  186 Qed  #5224897    1/25 peers   70 KiB chain 73 MiB db 23 MiB queue 152 KiB sync  RPC:  1 conn,  8 req/s,  78 µs

... Shortened by me because it does not contain any useful information

2018-04-19 22:45:23  Syncing #5225182 05e5…9bf3     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5225055    8/25 peers   6 MiB chain 108 MiB db 0 bytes queue 21 KiB sync  RPC:  1 conn,  1 req/s,  68 µs
2018-04-19 22:45:33  Syncing #5225182 05e5…9bf3     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5225055    9/25 peers   5 MiB chain 108 MiB db 0 bytes queue 21 KiB sync  RPC:  1 conn,  1 req/s,  76 µs
2018-04-19 22:45:43  Syncing #5225182 05e5…9bf3     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5225055    7/25 peers   5 MiB chain 108 MiB db 0 bytes queue 21 KiB sync  RPC:  1 conn,  0 req/s,  76 µs
2018-04-19 22:45:53  Syncing #5225182 05e5…9bf3     0 blk/s    0 tx/s   0 Mgas/s      0+    0 Qed  #5225055    5/25 peers   5 MiB chain 108 MiB db 0 bytes queue 21 KiB sync  RPC:  1 conn,  1 req/s,  86 µs

====================

stack backtrace:

Thread 'IO Worker #2' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', libcore/option.rs:917

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Abort trap: 6
```

Expected behavior: Sync complete or still syncing
Actual behaviour: Crashed

Maybe interesting to note: I copied my chain files from `~/Library/Application Support/io.parity.ethereum` to `/Volumes/EXTERNAL/Parity`, an external USB thumb drive before running sync. It ran for 4 hours before crashing. 

The config: (Pruning = archive wasn't active. I tried to do this on kovan but this did not work)
```toml
[parity]
db_path = "/Volumes/EXTERNAL/Parity"

# [footprint]
# pruning = "archive"
```

**Comment by jurglic** [comment]
I got into same issue, multiple times running `v1.10.2-beta` on MacOS. Mostly while syncing, as well as after sync.

**Comment by Tbaut** [comment]
Duplicates https://github.com/paritytech/parity/issues/5968
