### ISSUE TITLE
Make sure the spec file has a correct genesis seal

### ISSUE THREAD

**Issue by tomzuu** [paritytech/parity#8498]
I'm running:

**Which Parity version?**: 1.9.5-stable-ff821daf1-20180321
 **Which operating system?**: Linux Debian 4.9.65-3+deb9u1
**How installed?**: binaries
**Are you fully synchronized?**: yes
**Which network are you connected to?**: kovan
 **Did you try to restart the node?**: yes

2018-04-25 13:26:18 UTC IO Worker #3 DEBUG sync  Sent up to 3 transactions to 4 peers.
2018-04-25 13:26:20 UTC Verifier #1 INFO import  Imported #6998916 5d8bâ¦8314 (2 txs, 2.82 Mgas, 2.29 ms, 10.36 KiB)
2018-04-25 13:26:20 UTC IO Worker #3 DEBUG sync  Sent up to 1 transactions to 3 peers.
2018-04-25 13:26:22 UTC IO Worker #2 DEBUG sync  Sent up to 2 transactions to 4 peers.
2018-04-25 13:26:23 UTC IO Worker #3 DEBUG sync  Sent up to 1 transactions to 3 peers.

====================

stack backtrace:
   0:     0x55f0b6a2b90c - <no info>

Thread '<unnamed>' panicked at 'was either checked with verify_block_basic or is genesis; has 2 fields; qed (Make sure the spec file has a correct genesis seal)', /checkout/src/libcore/option.rs:891

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted

######################### NEXT RUN ##################################

2018-04-26 13:10:44 UTC Verifier #0 INFO import  Imported #7010867 2406â¦f529 (1 txs, 0.02 Mgas, 5.26 ms, 0.68 KiB)
2018-04-26 13:10:44 UTC IO Worker #2 INFO ethcore::snapshot::service  Snapshot: 94907 accounts 0 blocks 77749750 bytes
2018-04-26 13:10:45 UTC IO Worker #0 DEBUG sync  Sent up to 1 transactions to 3 peers.
2018-04-26 13:10:46 UTC IO Worker #3 DEBUG sync  Sent up to 2 transactions to 7 peers.
2018-04-26 13:10:47 UTC IO Worker #0 DEBUG sync  Sent up to 2 transactions to 1 peers.
2018-04-26 13:10:48 UTC IO Worker #0 DEBUG sync  Sent up to 2 transactions to 1 peers.
2018-04-26 13:10:49 UTC IO Worker #1 DEBUG sync  Sent up to 2 transactions to 1 peers.
2018-04-26 13:10:50 UTC IO Worker #0 DEBUG sync  Sent up to 1 transactions to 1 peers.
2018-04-26 13:10:51 UTC IO Worker #2 INFO import    25/25 peers   5 MiB chain 91 MiB db 0 bytes queue 94 KiB sync  RPC:  0 conn, 20 req/s, 136 Âµs
2018-04-26 13:10:51 UTC IO Worker #2 DEBUG sync  Sent up to 2 transactions to 2 peers.
2018-04-26 13:10:52 UTC IO Worker #2 DEBUG sync  Sent up to 2 transactions to 1 peers.
2018-04-26 13:10:54 UTC IO Worker #0 DEBUG sync  Sent up to 1 transactions to 5 peers.
2018-04-26 13:10:54 UTC IO Worker #3 INFO ethcore::snapshot::service  Snapshot: 94907 accounts 0 blocks 77749750 bytes
2018-04-26 13:10:55 UTC IO Worker #0 DEBUG sync  Sent up to 1 transactions to 3 peers.
2018-04-26 13:10:56 UTC IO Worker #0 DEBUG sync  Sent up to 1 transactions to 1 peers.
2018-04-26 13:10:57 UTC IO Worker #2 DEBUG sync  Sent up to 1 transactions to 1 peers.
2018-04-26 13:10:58 UTC IO Worker #3 DEBUG sync  Sent up to 1 transactions to 1 peers.
2018-04-26 13:10:59 UTC IO Worker #0 DEBUG sync  Sent up to 1 transactions to 3 peers.
2018-04-26 13:11:00 UTC IO Worker #1 DEBUG sync  Sent up to 1 transactions to 3 peers.

====================

stack backtrace:
   0:     0x5620bd18490c - <no info>

Thread '<unnamed>' panicked at 'was either checked with verify_block_basic or is genesis; has 2 fields; qed (Make sure the spec file has a correct genesis seal)', /checkout/src/libcore/option.rs:891

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

Aborted

**Comment by Tbaut** [comment]
Duplicates https://github.com/paritytech/parity/issues/7880
