### ISSUE TITLE
Filter gives constant empty array after some time

### ISSUE THREAD

**Issue by iFA88** [paritytech/parity#8741]
Greetings,
I have updated my node from 1.9.5-stable to `Parity/v1.10.4-stable-39b9f1e25-20180514/x86_64-linux-gnu/rustc1.25.0` and I run with `--tx-queue-mem-limit=1024 --tx-queue-size=128000` flags.
I have set up `eth_newPendingTransactionFilter` filter and I call `eth_getFilterChanges` in every 30 sec. For the first 10-15 minute works perfect, I receive the new pending transactions, and after this time I get only empty array `[]` (almost 6 hours). The filter ID is active, I don't receive any error message on query.
The `parity_pendingTransactions()` gives ~23000 length array, so this are working.
After I create new `eth_newPendingTransactionFilter` then with the new ID works again for 55 minutes, the old filter ID gives still empty array.
Restarting the node doens't helps.

**Comment by Tbaut** [comment]
Can you paste here the code that you are using?
As always, knowing what you want to achieve can help us point you in the right direction in case there are better ways to do. Can you explain why you need the new pending transactions?

**Comment by iFA88** [comment]
> Can you explain why you need the new pending transactions?

I would like to create a database from all pending transactions what my node receives for my own purposes. For example:
- Estimating new transactions processing time
- Display pending transactions on my web wallet

> Can you paste here the code that you are using?

I use https://github.com/iFA88/EthereumIPC for IPC client. The I can not past the whole code, but simplified looks so:
```python
filterID = ''
nodeode = EthereumIPC(IPC_LOCATION)
whilte True:
  if not filterID:
    filterID = node.eth_newPendingTransactionFilter()
  try:
    ptxs = node.eth_getFilterChanges(filterID)
  except Exception as err:
    if type(err.message) is dict and err.message['message'] == 'Filter not found':
      filterID = ""
      continue
  print len(ptxs)
  # processPTXs(ptxs)
  sleep(30)
```

I have downgraded the client to `Parity/v1.10.3-stable-b9ceda38a-20180507/x86_64-linux-gnu/rustc1.25.0` but its the same issue.. I will not downgrade to older stable versions.

**Comment by iFA88** [comment]
`Parity/v1.9.7-stable-7919629f3-20180423/x86_64-linux-gnu/rustc1.25.0`
Without any problem.
```
start
2018-05-31 09:25:57.574700 0
2018-05-31 09:26:31.579496 812
2018-05-31 09:27:01.613662 831
2018-05-31 09:27:31.645185 588
2018-05-31 09:28:01.676556 219
2018-05-31 09:28:32.866438 1400
2018-05-31 09:29:04.840055 71
2018-05-31 09:29:34.884678 5
2018-05-31 09:30:05.417756 846
2018-05-31 09:30:38.701819 246
2018-05-31 09:31:08.745035 3770
2018-05-31 09:31:38.807699 1088
2018-05-31 09:32:08.851872 509
2018-05-31 09:32:38.898087 601
2018-05-31 09:33:08.930436 163
2018-05-31 09:33:41.511769 280
2018-05-31 09:34:11.548792 356
2018-05-31 09:34:41.582033 18
2018-05-31 09:35:15.743305 70
2018-05-31 09:35:45.790363 5
2018-05-31 09:36:21.136758 416
2018-05-31 09:36:55.220568 488
2018-05-31 09:37:30.219308 439
2018-05-31 09:38:00.263009 546
2018-05-31 09:38:30.298110 507
2018-05-31 09:39:00.331562 299
2018-05-31 09:39:37.041778 321
2018-05-31 09:40:07.882919 105
2018-05-31 09:40:43.850462 171
2018-05-31 09:41:13.883590 227
2018-05-31 09:41:50.870469 13
2018-05-31 09:42:22.940316 363
2018-05-31 09:42:54.031224 95
2018-05-31 09:43:24.083011 38
2018-05-31 09:43:54.192651 601
2018-05-31 09:44:24.231669 153
2018-05-31 09:44:54.268064 171
2018-05-31 09:45:24.306552 494
2018-05-31 09:45:59.852868 231
2018-05-31 09:46:30.128601 7
2018-05-31 09:47:00.744721 0
2018-05-31 09:47:30.780196 652
2018-05-31 09:48:00.816024 602
2018-05-31 09:48:32.041248 14
2018-05-31 09:49:02.075878 14
2018-05-31 09:49:32.123854 113
2018-05-31 09:50:05.528598 0
2018-05-31 09:50:37.753631 695
2018-05-31 09:51:08.744549 202
2018-05-31 09:51:40.495373 81
2018-05-31 09:52:13.880359 40
2018-05-31 09:52:49.428898 393
2018-05-31 09:53:19.465046 703
2018-05-31 09:53:53.528350 112
2018-05-31 09:54:23.595247 48
2018-05-31 09:54:57.157224 740
2018-05-31 09:55:36.777658 6090
2018-05-31 09:56:06.816004 702
2018-05-31 09:56:36.857112 598
2018-05-31 09:57:06.890989 444
2018-05-31 09:57:36.901666 1331
2018-05-31 09:58:06.936185 1273
2018-05-31 09:58:36.971238 347
2018-05-31 09:59:07.007568 429
2018-05-31 09:59:42.656722 123
2018-05-31 10:00:14.969794 569
2018-05-31 10:00:45.003847 295
2018-05-31 10:01:15.052996 362
2018-05-31 10:01:45.088595 0
2018-05-31 10:02:15.135780 531
2018-05-31 10:02:45.163848 1038
2018-05-31 10:03:16.544688 310
2018-05-31 10:03:46.595482 7
2018-05-31 10:04:17.013764 0
2018-05-31 10:04:59.170162 635
2018-05-31 10:05:29.242087 1495
2018-05-31 10:06:04.727180 1083
2018-05-31 10:06:38.673380 629
2018-05-31 10:07:11.509827 4273
2018-05-31 10:07:41.554163 721
2018-05-31 10:08:11.592283 184
2018-05-31 10:08:41.635657 882
2018-05-31 10:09:13.140721 0
2018-05-31 10:09:43.746435 775
2018-05-31 10:10:13.796694 134
2018-05-31 10:10:44.612868 422
2018-05-31 10:11:21.568799 71
2018-05-31 10:11:51.604881 934
2018-05-31 10:12:21.666844 3642
2018-05-31 10:12:57.615502 419
2018-05-31 10:13:32.752630 16
2018-05-31 10:14:13.027890 34
2018-05-31 10:14:43.760288 0
2018-05-31 10:15:14.331592 29
2018-05-31 10:15:44.367908 285
2018-05-31 10:16:14.403724 1
2018-05-31 10:16:50.875186 143
2018-05-31 10:17:28.175539 1052
2018-05-31 10:18:01.357383 156
2018-05-31 10:18:34.445049 266
2018-05-31 10:19:27.348152 7924
2018-05-31 10:19:57.394966 10
2018-05-31 10:20:27.435454 13
2018-05-31 10:20:57.476768 1758
2018-05-31 10:21:31.403959 34
2018-05-31 10:22:06.579439 91
2018-05-31 10:22:42.448711 93
2018-05-31 10:23:16.765251 27
2018-05-31 10:23:51.196169 0
2018-05-31 10:24:23.196690 114
2018-05-31 10:24:54.235137 177
2018-05-31 10:25:24.274102 455
2018-05-31 10:25:57.325469 21
2018-05-31 10:26:36.003175 78
2018-05-31 10:27:07.316014 42
2018-05-31 10:27:45.336961 7
2018-05-31 10:28:22.965722 22
2018-05-31 10:28:58.207179 536
2018-05-31 10:29:28.261288 228
2018-05-31 10:29:58.305353 845
2018-05-31 10:30:31.295115 170
2018-05-31 10:31:01.339203 58
2018-05-31 10:31:39.688587 0
2018-05-31 10:32:10.221413 9
2018-05-31 10:32:43.100666 3380
2018-05-31 10:33:13.137092 393
2018-05-31 10:33:43.252483 308
2018-05-31 10:34:13.288202 199
2018-05-31 10:34:47.891879 156
2018-05-31 10:35:17.964989 1
2018-05-31 10:35:48.006338 376
2018-05-31 10:36:18.040557 796
2018-05-31 10:36:48.083801 82
2018-05-31 10:37:23.477036 1539
2018-05-31 10:37:53.513582 1136
2018-05-31 10:38:23.556327 726
2018-05-31 10:38:53.759702 763
2018-05-31 10:39:23.816764 240
2018-05-31 10:39:56.656832 1198
2018-05-31 10:40:26.691083 15
2018-05-31 10:40:57.522188 1776
2018-05-31 10:41:27.557171 1133
2018-05-31 10:42:03.104431 5943
2018-05-31 10:42:38.164444 39
2018-05-31 10:43:12.189828 38
2018-05-31 10:43:42.237327 14
2018-05-31 10:44:12.431080 0
2018-05-31 10:44:47.393088 724
2018-05-31 10:45:19.932829 147
2018-05-31 10:45:49.968209 23
2018-05-31 10:46:26.468839 347
2018-05-31 10:46:56.527808 1060
2018-05-31 10:47:44.726075 1913
2018-05-31 10:48:16.118122 1
2018-05-31 10:48:46.153318 23
2018-05-31 10:49:17.636597 9
2018-05-31 10:49:52.566339 833
2018-05-31 10:50:22.877682 768
2018-05-31 10:50:52.920906 540
2018-05-31 10:51:22.955788 705
2018-05-31 10:51:53.572230 194
2018-05-31 10:52:24.799482 143
2018-05-31 10:52:54.835457 58
2018-05-31 10:53:24.872526 203
2018-05-31 10:53:54.910517 27
2018-05-31 10:54:24.947684 22
2018-05-31 10:54:54.983783 3
2018-05-31 10:55:25.020982 930
2018-05-31 10:55:55.065895 201
2018-05-31 10:56:25.465652 447
2018-05-31 10:56:57.092311 34
2018-05-31 10:57:27.128704 533
2018-05-31 10:57:57.377406 687
2018-05-31 10:58:30.697164 489
2018-05-31 10:59:00.733005 526
2018-05-31 10:59:30.769275 589
2018-05-31 11:00:02.945570 63
2018-05-31 11:00:32.983991 8
2018-05-31 11:01:05.455819 72
2018-05-31 11:01:37.328846 254
2018-05-31 11:02:07.368307 574
2018-05-31 11:02:37.508667 850
2018-05-31 11:03:10.152924 197
2018-05-31 11:03:45.295606 289
2018-05-31 11:04:17.686949 110
2018-05-31 11:04:47.748582 8
2018-05-31 11:05:17.787269 399
2018-05-31 11:05:47.833872 1067
2018-05-31 11:06:17.873500 1052
2018-05-31 11:06:47.909390 1071
```

**Comment by Tbaut** [comment]
Thanks for the details.
cc @tomusdrw or @debris could help us shed some light on what might go wrong here.

**Comment by iFA88** [comment]
If I give a Filter ID which not exist, then I didn't get any error message, not even in (STABLE) 1.9.4 / 1.9.5 / 1.9.7 / 1.10.3 / 1.10.4.

For example:
```
.eth_getFilterChanges(666)
Traceback: Traceback (most recent call last):
  File "/usr/bin/nodeConsole.py", line 83, in <module>
    r = eval(cmd)
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/ethereumIPC.py", line 82, in _request
    raise RequestErrorResult(result['error'])
RequestErrorResult: {u'message': u'Invalid params: invalid type: integer `666`, expected a hex-encoded or decimal index.', u'code': -32602}

Error: {u'message': u'Invalid params: invalid type: integer `666`, expected a hex-encoded or decimal index.', u'code': -32602}
Give command:
.eth_getFilterChanges('0x29a')
[]
```

On beta 1.11.1 I receive the message `{u'message': u'Filter not found', u'code': -32000}`

**Comment by iFA88** [comment]
If you see my first log:
```
2018-05-31 09:03:09.984189 221
2018-05-31 09:05:26.610659 26523
```
There is 137 second delay, maybe the filter have uninstalled itself because timeout ( https://wiki.parity.io/JSONRPC-eth-module#eth_uninstallfilter ) And when I request I receive empty array bevcause the filter did not exist anymore and the error is missing.

**Comment by sorpaas** [comment]
@iFA88 Yes. The current `POLL_TIMEOUT` is 60 seconds, which means if there's no query after a minute, the filter will be uninstalled. Before 1.11, when querying an non-existing filter id, it would return empty array. On 1.11, this is changed to return "Filter not found" error.

So I think if you upgrade to 1.11, the code snippets you provided (https://github.com/paritytech/parity/issues/8741#issuecomment-393426617) will work as expected.

**Comment by iFA88** [comment]
@sorpaas Thank you, then I think right. Sadly there is no 1.11.x stable version.

I think this case is solved. Thanks!
